import { isValidElement } from 'react';
import {
  Activity,
  BadgeCheck,
  BadgePlus,
  BellRing,
  BookOpen,
  Building2,
  CakeSlice,
  CalendarDays,
  Castle,
  ChartNoAxesColumnIncreasing,
  ChevronsUp,
  CircleHelp,
  CircleOff,
  CirclePlay,
  Clock3,
  CloudFog,
  CloudSun,
  Coins,
  Compass,
  Construction,
  CookingPot,
  Crown,
  Crosshair,
  Download,
  Droplets,
  Dumbbell,
  Dices,
  FastForward,
  FileSignature,
  FileText,
  Flag,
  Flame,
  FlaskConical,
  FolderOpen,
  Gauge,
  GalleryVerticalEnd,
  Gavel,
  Gift,
  GraduationCap,
  Grid3X3,
  Hammer,
  Handshake,
  HeartHandshake,
  HeartCrack,
  HeartPulse,
  Hourglass,
  Layers3,
  LayoutTemplate,
  Lightbulb,
  Link2,
  ListPlus,
  LockKeyhole,
  Map,
  MapPin,
  Medal,
  MoonStar,
  Move,
  Network,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PartyPopper,
  Pause,
  Pickaxe,
  Plane,
  RefreshCw,
  Receipt,
  Recycle,
  Radio,
  RadioTower,
  Repeat2,
  RotateCcw,
  RotateCw,
  Save,
  ScanLine,
  School,
  Search,
  ScrollText,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldOff,
  Shuffle,
  ShoppingCart,
  SkipForward,
  Skull,
  Sparkles,
  Sprout,
  Star,
  Store,
  Soup,
  Swords,
  Target,
  TentTree,
  Terminal,
  Timer,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Trophy,
  Utensils,
  UsersRound,
  Volume2,
  VolumeX,
  Wrench,
  X,
  Zap,
} from 'lucide-react';
import { inferGameActionSemantic } from '../_lib/gameActionSemantics';

const ACTION_ICONS = {
  action: CirclePlay,
  'answer-maybe': CircleHelp,
  'answer-no': X,
  'answer-yes': BadgeCheck,
  advance: FastForward,
  analysis: Gauge,
  advisor: Gauge,
  attack: Crosshair,
  assign: ListPlus,
  archive: FileText,
  audio: Volume2,
  auto: FastForward,
  buff: TrendingUp,
  burst: Crosshair,
  calendar: CalendarDays,
  camp: TentTree,
  cards: Layers3,
  deck: GalleryVerticalEnd,
  defeat: X,
  draw: Layers3,
  duel: Swords,
  effect: Zap,
  champion: Crown,
  close: X,
  clock: Clock3,
  claim: Gift,
  code: Terminal,
  combat: Swords,
  comeback: TrendingUp,
  complete: BadgeCheck,
  confirm: BadgeCheck,
  counsel: HeartHandshake,
  cook: CookingPot,
  cup: Medal,
  fry: CookingPot,
  grill: Flame,
  boil: Soup,
  simmer: Timer,
  sauce: Droplets,
  dessert: CakeSlice,
  contract: FileSignature,
  collection: Coins,
  'cover-break': ShieldOff,
  consume: Utensils,
  craft: Hammer,
  defend: Shield,
  debuff: TrendingDown,
  dispatch: TrainFront,
  diplomacy: Network,
  discover: Compass,
  download: Download,
  draft: Terminal,
  disclosure: ScrollText,
  dividend: Coins,
  deploy: Flag,
  edict: ScrollText,
  equip: PackageCheck,
  elimination: Skull,
  event: Zap,
  execute: CirclePlay,
  festival: PartyPopper,
  favorite: Star,
  finance: ChartNoAxesColumnIncreasing,
  filter: Shuffle,
  fuel: Flame,
  gather: Pickaxe,
  guide: BookOpen,
  guard: ShieldCheck,
  growth: Sprout,
  guess: Target,
  hint: Lightbulb,
  inventory: PackageOpen,
  import: PackageOpen,
  inspect: Search,
  judge: Gavel,
  kitchen: CookingPot,
  lesson: GraduationCap,
  load: FolderOpen,
  'logo-audit': ScanLine,
  'logo-perfect': BadgeCheck,
  lock: LockKeyhole,
  map: Map,
  match: Radio,
  miss: CircleOff,
  move: Move,
  new: Sparkles,
  order: PackageCheck,
  'pack-apply': PackageCheck,
  'pack-clear': PackageMinus,
  'pack-invalid': CircleOff,
  overwatch: ScanLine,
  pause: Pause,
  pass: SkipForward,
  phase: SkipForward,
  position: RotateCw,
  property: Building2,
  project: Construction,
  production: Hammer,
  question: CircleHelp,
  preset: LayoutTemplate,
  policy: Gavel,
  'primitive-camp': TentTree,
  'primitive-civic': Gavel,
  'primitive-craft': Hammer,
  'primitive-day': CalendarDays,
  'primitive-defeat': Skull,
  'primitive-diplomacy': Handshake,
  'primitive-discovery': Compass,
  'primitive-equip': PackageCheck,
  'primitive-era': Castle,
  'primitive-eureka': Lightbulb,
  'primitive-event': Zap,
  'primitive-gather': Pickaxe,
  'primitive-growth': Sprout,
  'primitive-hunt': Crosshair,
  'primitive-inspiration': Sparkles,
  'primitive-job': UsersRound,
  'primitive-meal': Utensils,
  'primitive-perk': Star,
  'primitive-project': Construction,
  'primitive-recruit': BadgePlus,
  'primitive-region': MapPin,
  'primitive-research': FlaskConical,
  'primitive-rest': MoonStar,
  'primitive-season': CloudSun,
  'primitive-survival-fail': HeartCrack,
  'primitive-victory': Trophy,
  recruit: BadgePlus,
  refresh: RefreshCw,
  revive: HeartPulse,
  release: PackageMinus,
  'release-ready': Trophy,
  research: FlaskConical,
  'race-card': Flag,
  reset: RotateCcw,
  rest: MoonStar,
  replay: FileText,
  reroll: Dices,
  ride: ChevronsUp,
  save: Save,
  salvage: Recycle,
  sales: Receipt,
  shipment: PackageCheck,
  snapshot: Save,
  school: School,
  season: CloudSun,
  'season-card': CalendarDays,
  semester: BellRing,
  station: MapPin,
  search: Search,
  settings: Settings2,
  signal: RadioTower,
  shop: ShoppingCart,
  shuffle: Shuffle,
  skill: Zap,
  smoke: CloudFog,
  set: Shield,
  spell: Sparkles,
  sponsor: Handshake,
  support: HeartHandshake,
  serve: Utensils,
  summon: GalleryVerticalEnd,
  survival: TentTree,
  status: Activity,
  kiosk: Store,
  drone: Plane,
  mute: VolumeX,
  players: UsersRound,
  sync: RefreshCw,
  tactics: Grid3X3,
  target: Target,
  trap: ShieldCheck,
  title: Medal,
  tower: Castle,
  tournament: Trophy,
  trade: Coins,
  tax: Receipt,
  transfer: Repeat2,
  training: Dumbbell,
  unequip: PackageOpen,
  turn: RotateCw,
  'unit-down': HeartCrack,
  trophy: Trophy,
  upgrade: Wrench,
  valuation: Search,
  'vanguard-attack': Crosshair,
  'vanguard-blocked': ShieldOff,
  'vanguard-call': GalleryVerticalEnd,
  'vanguard-damage': HeartCrack,
  'vanguard-deck-out': PackageMinus,
  'vanguard-defeat': Skull,
  'vanguard-draw': Layers3,
  'vanguard-guard': ShieldCheck,
  'vanguard-guard-window': Shield,
  'vanguard-hit': Target,
  'vanguard-invalid': CircleOff,
  'vanguard-perfect-guard': BadgeCheck,
  'vanguard-replay': FileText,
  'vanguard-retire': HeartCrack,
  'vanguard-ride': ChevronsUp,
  'vanguard-skill': Zap,
  'vanguard-stride': Sparkles,
  'vanguard-trigger': Zap,
  'vanguard-turn': RotateCw,
  'vanguard-victory': Trophy,
  settle: Receipt,
  capital: ChartNoAxesColumnIncreasing,
  closing: CalendarDays,
  export: Plane,
  hedge: ShieldCheck,
  ledger: FileText,
  restore: RefreshCw,
  bookmark: Star,
  zone: Layers3,
  chain: Link2,
  formation: Grid3X3,
  wait: Hourglass,
  verdict: Gavel,
  victory: Trophy,
  warning: BellRing,
  winners: UsersRound,
  board: Grid3X3,
  hand: Layers3,
  logs: FileText,
  room: Network,
};

export function gameActionText(children) {
  if (children === null || children === undefined || typeof children === 'boolean') return '';
  if (typeof children === 'string' || typeof children === 'number') return String(children);
  if (Array.isArray(children)) return children.map((child) => gameActionText(child)).join(' ');
  if (isValidElement(children)) return gameActionText(children.props.children);
  return '';
}

export function resolveGameAction(action, ...labels) {
  const explicit = String(action || '').trim();
  if (explicit && ACTION_ICONS[explicit]) {
    const inferred = inferGameActionSemantic(explicit, labels);
    return { kind: explicit, cue: inferred.cue };
  }
  return inferGameActionSemantic(explicit, labels);
}

export default function GameActionIcon({ action, label = '', className = '' }) {
  const semantic = resolveGameAction(action, label);
  const Icon = ACTION_ICONS[semantic.kind] || CirclePlay;
  return (
    <span className={`game-action-icon${className ? ` ${className}` : ''}`} aria-hidden="true">
      <Icon size={18} strokeWidth={2.2} />
    </span>
  );
}
