import { isValidElement } from 'react';
import {
  BadgeCheck,
  BadgePlus,
  BookOpen,
  Building2,
  CalendarDays,
  Castle,
  ChartNoAxesColumnIncreasing,
  ChevronsUp,
  CirclePlay,
  CloudSun,
  Coins,
  Compass,
  Construction,
  CookingPot,
  Crosshair,
  Download,
  Dumbbell,
  Dices,
  FastForward,
  FileText,
  Flag,
  Flame,
  FlaskConical,
  FolderOpen,
  Gauge,
  GalleryVerticalEnd,
  Gavel,
  Gift,
  Grid3X3,
  Hammer,
  Hourglass,
  Layers3,
  LayoutTemplate,
  Link2,
  ListPlus,
  LockKeyhole,
  Map,
  Medal,
  MoonStar,
  Move,
  Network,
  PackageOpen,
  PackageCheck,
  Pickaxe,
  RefreshCw,
  Receipt,
  Recycle,
  RotateCcw,
  RotateCw,
  Save,
  School,
  Search,
  ScrollText,
  Settings2,
  Shield,
  ShieldCheck,
  Shuffle,
  ShoppingCart,
  SkipForward,
  Sparkles,
  Sprout,
  Swords,
  Target,
  TentTree,
  Terminal,
  TrainFront,
  Trophy,
  Utensils,
  Wrench,
  X,
  Zap,
} from 'lucide-react';
import { inferGameActionSemantic } from '../_lib/gameActionSemantics';

const ACTION_ICONS = {
  action: CirclePlay,
  advance: FastForward,
  analysis: Gauge,
  assign: ListPlus,
  archive: FileText,
  auto: FastForward,
  calendar: CalendarDays,
  camp: TentTree,
  cards: Layers3,
  close: X,
  claim: Gift,
  code: Terminal,
  combat: Swords,
  complete: BadgeCheck,
  consume: Utensils,
  craft: Hammer,
  defend: Shield,
  dispatch: TrainFront,
  diplomacy: Network,
  discover: Compass,
  download: Download,
  deploy: Flag,
  edict: ScrollText,
  equip: PackageCheck,
  event: Zap,
  execute: CirclePlay,
  finance: ChartNoAxesColumnIncreasing,
  fuel: Flame,
  gather: Pickaxe,
  guide: BookOpen,
  guard: ShieldCheck,
  growth: Sprout,
  inventory: PackageOpen,
  judge: Gavel,
  kitchen: CookingPot,
  load: FolderOpen,
  lock: LockKeyhole,
  map: Map,
  move: Move,
  new: Sparkles,
  pass: SkipForward,
  property: Building2,
  project: Construction,
  preset: LayoutTemplate,
  recruit: BadgePlus,
  research: FlaskConical,
  reset: RotateCcw,
  rest: MoonStar,
  replay: FileText,
  reroll: Dices,
  ride: ChevronsUp,
  save: Save,
  salvage: Recycle,
  school: School,
  season: CloudSun,
  search: Search,
  settings: Settings2,
  shop: ShoppingCart,
  shuffle: Shuffle,
  skill: Zap,
  summon: GalleryVerticalEnd,
  survival: TentTree,
  sync: RefreshCw,
  tactics: Grid3X3,
  target: Target,
  title: Medal,
  tower: Castle,
  trade: Coins,
  training: Dumbbell,
  turn: RotateCw,
  trophy: Trophy,
  upgrade: Wrench,
  settle: Receipt,
  zone: Layers3,
  chain: Link2,
  formation: Grid3X3,
  wait: Hourglass,
};

export function gameActionText(children) {
  if (children === null || children === undefined || typeof children === 'boolean') return '';
  if (typeof children === 'string' || typeof children === 'number') return String(children);
  if (Array.isArray(children)) return children.map((child) => gameActionText(child)).join(' ');
  if (isValidElement(children)) return gameActionText(children.props.children);
  return '';
}

export function resolveGameAction(action, ...labels) {
  const explicit = String(action || '').trim();
  if (explicit && ACTION_ICONS[explicit]) {
    const inferred = inferGameActionSemantic(explicit, labels);
    return { kind: explicit, cue: inferred.cue };
  }
  return inferGameActionSemantic(explicit, labels);
}

export default function GameActionIcon({ action, label = '', className = '' }) {
  const semantic = resolveGameAction(action, label);
  const Icon = ACTION_ICONS[semantic.kind] || CirclePlay;
  return (
    <span className={`game-action-icon${className ? ` ${className}` : ''}`} aria-hidden="true">
      <Icon size={18} strokeWidth={2.2} />
    </span>
  );
}
