import { isValidElement } from 'react';
import {
  BadgeCheck,
  BadgePlus,
  BellRing,
  BookOpen,
  Building2,
  CakeSlice,
  CalendarDays,
  Castle,
  ChartNoAxesColumnIncreasing,
  ChevronsUp,
  CircleHelp,
  CircleOff,
  CirclePlay,
  Clock3,
  CloudSun,
  Coins,
  Compass,
  Construction,
  CookingPot,
  Crown,
  Crosshair,
  Download,
  Droplets,
  Dumbbell,
  Dices,
  FastForward,
  FileSignature,
  FileText,
  Flag,
  Flame,
  FlaskConical,
  FolderOpen,
  Gauge,
  GalleryVerticalEnd,
  Gavel,
  Gift,
  GraduationCap,
  Grid3X3,
  Hammer,
  Handshake,
  HeartHandshake,
  HeartCrack,
  HeartPulse,
  Hourglass,
  Layers3,
  LayoutTemplate,
  Lightbulb,
  Link2,
  ListPlus,
  LockKeyhole,
  Map,
  Medal,
  MoonStar,
  Move,
  Network,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PartyPopper,
  Pause,
  Pickaxe,
  Plane,
  RefreshCw,
  Receipt,
  Recycle,
  Radio,
  RadioTower,
  Repeat2,
  RotateCcw,
  RotateCw,
  Save,
  School,
  Search,
  ScrollText,
  Settings2,
  Shield,
  ShieldCheck,
  Shuffle,
  ShoppingCart,
  SkipForward,
  Skull,
  Sparkles,
  Sprout,
  Store,
  Soup,
  Swords,
  Target,
  TentTree,
  Terminal,
  Timer,
  TrainFront,
  TrendingUp,
  Trophy,
  Utensils,
  UsersRound,
  Volume2,
  VolumeX,
  Wrench,
  X,
  Zap,
} from 'lucide-react';
import { inferGameActionSemantic } from '../_lib/gameActionSemantics';

const ACTION_ICONS = {
  action: CirclePlay,
  'answer-maybe': CircleHelp,
  'answer-no': X,
  'answer-yes': BadgeCheck,
  advance: FastForward,
  analysis: Gauge,
  advisor: Gauge,
  attack: Crosshair,
  assign: ListPlus,
  archive: FileText,
  audio: Volume2,
  auto: FastForward,
  calendar: CalendarDays,
  camp: TentTree,
  cards: Layers3,
  deck: GalleryVerticalEnd,
  defeat: X,
  draw: Layers3,
  duel: Swords,
  effect: Zap,
  champion: Crown,
  close: X,
  clock: Clock3,
  claim: Gift,
  code: Terminal,
  combat: Swords,
  comeback: TrendingUp,
  complete: BadgeCheck,
  confirm: BadgeCheck,
  counsel: HeartHandshake,
  cook: CookingPot,
  fry: CookingPot,
  grill: Flame,
  boil: Soup,
  simmer: Timer,
  sauce: Droplets,
  dessert: CakeSlice,
  contract: FileSignature,
  consume: Utensils,
  craft: Hammer,
  defend: Shield,
  dispatch: TrainFront,
  diplomacy: Network,
  discover: Compass,
  download: Download,
  deploy: Flag,
  edict: ScrollText,
  equip: PackageCheck,
  elimination: Skull,
  event: Zap,
  execute: CirclePlay,
  festival: PartyPopper,
  finance: ChartNoAxesColumnIncreasing,
  fuel: Flame,
  gather: Pickaxe,
  guide: BookOpen,
  guard: ShieldCheck,
  growth: Sprout,
  guess: Target,
  hint: Lightbulb,
  inventory: PackageOpen,
  inspect: Search,
  judge: Gavel,
  kitchen: CookingPot,
  lesson: GraduationCap,
  load: FolderOpen,
  lock: LockKeyhole,
  map: Map,
  match: Radio,
  miss: CircleOff,
  move: Move,
  new: Sparkles,
  order: PackageCheck,
  pause: Pause,
  pass: SkipForward,
  phase: SkipForward,
  position: RotateCw,
  property: Building2,
  project: Construction,
  question: CircleHelp,
  preset: LayoutTemplate,
  policy: Gavel,
  recruit: BadgePlus,
  refresh: RefreshCw,
  revive: HeartPulse,
  release: PackageMinus,
  research: FlaskConical,
  reset: RotateCcw,
  rest: MoonStar,
  replay: FileText,
  reroll: Dices,
  ride: ChevronsUp,
  save: Save,
  salvage: Recycle,
  sales: Receipt,
  school: School,
  season: CloudSun,
  semester: BellRing,
  search: Search,
  settings: Settings2,
  signal: RadioTower,
  shop: ShoppingCart,
  shuffle: Shuffle,
  skill: Zap,
  set: Shield,
  spell: Sparkles,
  sponsor: Handshake,
  serve: Utensils,
  summon: GalleryVerticalEnd,
  survival: TentTree,
  kiosk: Store,
  drone: Plane,
  mute: VolumeX,
  players: UsersRound,
  sync: RefreshCw,
  tactics: Grid3X3,
  target: Target,
  trap: ShieldCheck,
  title: Medal,
  tower: Castle,
  tournament: Trophy,
  trade: Coins,
  transfer: Repeat2,
  training: Dumbbell,
  turn: RotateCw,
  'unit-down': HeartCrack,
  trophy: Trophy,
  upgrade: Wrench,
  settle: Receipt,
  zone: Layers3,
  chain: Link2,
  formation: Grid3X3,
  wait: Hourglass,
  verdict: Gavel,
  victory: Trophy,
  warning: BellRing,
  board: Grid3X3,
  hand: Layers3,
  logs: FileText,
  room: Network,
};

export function gameActionText(children) {
  if (children === null || children === undefined || typeof children === 'boolean') return '';
  if (typeof children === 'string' || typeof children === 'number') return String(children);
  if (Array.isArray(children)) return children.map((child) => gameActionText(child)).join(' ');
  if (isValidElement(children)) return gameActionText(children.props.children);
  return '';
}

export function resolveGameAction(action, ...labels) {
  const explicit = String(action || '').trim();
  if (explicit && ACTION_ICONS[explicit]) {
    const inferred = inferGameActionSemantic(explicit, labels);
    return { kind: explicit, cue: inferred.cue };
  }
  return inferGameActionSemantic(explicit, labels);
}

export default function GameActionIcon({ action, label = '', className = '' }) {
  const semantic = resolveGameAction(action, label);
  const Icon = ACTION_ICONS[semantic.kind] || CirclePlay;
  return (
    <span className={`game-action-icon${className ? ` ${className}` : ''}`} aria-hidden="true">
      <Icon size={18} strokeWidth={2.2} />
    </span>
  );
}
