// client/src/utils/statusLogic.js
export {
  EFFECT_AIRBORNE,
  EFFECT_BURN,
  EFFECT_COOLDOWN_DOWN,
  EFFECT_COOLDOWN_UP,
  EFFECT_FOCUS,
  EFFECT_FOOD_POISON,
  EFFECT_HASTE,
  EFFECT_HEAL_REDUCTION,
  EFFECT_KNOCKBACK,
  EFFECT_LIFESTEAL,
  EFFECT_META,
  EFFECT_POISON,
  EFFECT_REGEN,
  EFFECT_SHIELD,
  EFFECT_SLOW,
  EFFECT_STIM,
  EFFECT_STUN,
  EFFECT_ROOT,
  EFFECT_SILENCE,
  EFFECT_INVULNERABLE,
  EFFECT_UNTARGETABLE,
  EFFECT_BLIND,
  EFFECT_EVADE,
  EFFECT_MOVEMENT_IMMUNE,
  EFFECT_UNSTOPPABLE,
  EFFECT_CC_IMMUNE,
  EFFECT_HARMFUL_IMMUNE,
  EFFECT_CLEANSE,
  EFFECT_FEAR,
  EFFECT_CHARM,
  EFFECT_TAUNT,
  EFFECT_SLEEP,
  EFFECT_POLYMORPH,
  EFFECT_SUPPRESSION,
  EFFECT_STASIS,
  getStoredActiveStatusEffects,
  getStatusProtectionReason,
  isCrowdControlEffect,
  isHarmfulStatusEffect,
  canReduceControlDuration,
  getActiveStatusEffects,
  canonicalizeEffectName,
  makeCooldownRateEffect,
  makeHealReductionEffect,
  makeLifestealEffect,
  makeMoveSpeedEffect,
  makeRegenEffect,
  makeShieldEffect,
  makeStatBuffEffect,
  makeStatusValueEffect,
  normalizeStatusEffect,
  normalizeStatusEffectList,
} from './statusEffectDefinitions.js';

export {
  applyHealingModifier,
  getCooldownTickMultiplier,
  getEffectStacks,
  getEffectValueTotal,
  getHealReductionPct,
  getKnockbackDistance,
  getLifestealPercent,
  getMoveSpeedStatusBonus,
  getRegenValue,
  getShieldValue,
  hasActionBlockStatus,
  hasMovementInterruptStatus,
  getCollarPausedSeconds,
  isForcedControlEffect,
  getForcedControlEffect,
  canActVoluntarilyByStatus,
  canBasicAttackByStatus,
  canMoveByStatus,
  canUseSkillByStatus,
  isTargetableByStatus,
  getDamageBlockReason,
  getNewDamageProtectedSeconds,
} from './statusEffectSelectors.js';

export {
  absorbShieldDamage,
  addOrRefreshEffect,
  hasEffectImmunity,
  purgeNegativeEffects,
  updateEffects,
  getStatusDurationAdjustment,
} from './statusEffectApplication.js';

export { getEffectiveStats } from './statusEffectiveStats.js';
