import {
  itemDisplayName,
  itemIcon,
  clampTier4,
  compactIO,
  crateTypeLabel,
  extractActorNameFromLog,
  findItemByKeywords,
  hash32,
  normalizeRewardDropEntries,
  normalizeMatchKey,
  pickWeighted,
  randInt,
  resolveRewardDropEntry,
  safeTags,
  shuffleArray,
  shortText,
  tierLabelKo,
  uniqStr,
} from './simulationCommon';
import {
  EQUIP_SLOTS,
  INIT_DEPENDENCY_PATHS,
  LUMIA_DEFAULT_EDGES,
  LUMIA_ZONE_POS,
  SLOT_ICON,
  START_WEAPON_TYPES,
} from './simulationConstants';
import {
  mergeStoredUserProgress,
  normalizeUserStatistics,
  saveLocalHallOfFameBackup,
} from './userProgress';
import {
  getTimeOfDayFromPhase,
  isAtOrAfterWorldTime,
  worldPhaseIndex,
  worldTimeText,
} from './worldTime';
import {
  PERK_EFFECT_ALIASES,
  PERK_EFFECT_DEFAULTS,
  applyPerkBundleToActor,
  applyPerkCreditBonus,
  applyPerkDamageReduction,
  applyPerkDiscount,
  applyPerkLootWeight,
  buildPerkRuntimeBundle,
  getActorPerkEffects,
  getPerkAggressionBias,
  getPerkEventItemBias,
  getPerkLootBias,
  getPerkWildlifeLootBias,
  maybeBoostDropQty,
  normalizePerkEffects,
  normalizePerkPct,
  perkNumber,
} from './perkRuntime';
import {
  DEFAULT_INV_RULES,
  addItemToInventory,
  canReceiveItem,
  consumeIngredientsFromInv,
  formatInvAddNote,
  formatInvRuleState,
  getInvItemId,
  getInvRules,
  getSimEquipExternalId,
  inferEquipSlot,
  inferItemCategory,
  invQty,
  isBandageLikeItem,
  isSimGeneratedEquipment,
  normalizeInventory,
} from './inventoryRules';
import {
  applyRegenEffect,
  applyRuntimeEffectPayloads,
  applyShieldEffect,
  applyStatusEffect,
  clearNegativeStatusEffects,
  clearPostCombatEffects,
  consumeShieldDamage,
  describeRuntimeEffect,
  getEffectIndex,
  hasActiveEffect,
  normalizeRuntimeEffect,
  removeActiveEffect,
} from './runtimeStatus';
import {
  getHyperloopDeviceZoneId,
  getMutantWildlifeSpawnZoneId,
  getScenarioEventTimeOfDay,
  isEnabledScenarioEvent,
  localKeyHyperloopDeviceZone,
  localKeyHyperloops,
  localKeyMutantWildlifeZone,
  readLocalJsonArray,
  readLocalString,
} from './localSimulationSettings';
import {
  applyEquipTier,
  buildCraftGoal,
  buildCraftDebugInfo,
  classifySpecialByName,
  computeCraftTierFromIngredients,
  getOneSpecialShortMissing,
  isItemInMapCrates,
  isSpecialCoreKind,
  normalizeGoalTier,
  pickBestEquipBySlot,
  pickGoalLoadoutBySlot,
  pickGoalLoadoutKeys,
  tryAutoCraftFromLoot,
} from './craftRuntime';
import {
  canUseKioskAtWorldTime,
  countInventoryUnits,
  hasKioskAtZone,
  kioskLegendaryPrice,
  zoneNameHasKiosk,
} from './marketRuntime';
import {
  findCrateZoneIdsForItem,
  findCrateZoneWeightsForItem,
  listKioskZoneIdsForMap,
  uniqStrings,
} from './mapTargeting';
import {
  buildRuntimeSurvivorMap,
  ensureEquipped,
  getEquipMoveSpeed,
  getEquipSummary,
  getEquipTierSummary,
  normalizeRuntimeInventory,
  normalizeRuntimeSurvivor,
  normalizeRuntimeSurvivorList,
  upsertRuntimeSurvivor,
} from './survivorRuntime';
import {
  pickFromAllCrates,
} from './lootRuntime';
import {
  readStat,
  roughPower,
} from './combatRuntime';
import {
  consumeWildlifeAtZone,
  rollWildlifeEncounter,
} from './wildlifeRuntime';
import {
  LEGACY_CORE_ZONE_IDS,
  LEGACY_CORE_ZONE_NAME_KEYS,
  getEligibleCoreSpawnZoneIds,
  getEligibleSpawnZoneIds,
  rollNaturalCoreSpawn,
  zoneAllowsNaturalCore,
  zoneHasKioskFlag,
} from './coreSpawnRuntime';
import {
  cloneSpawnState,
  createInitialSpawnState,
} from './spawnStateRuntime';
import {
  getLegendaryCoreCandidates,
  resolveLegendaryDropWeights,
  rollLegendaryCrateLoot,
} from './legendaryRuntime';
import {
  consumeBossAtZone,
  consumeMutantWildlifeAtZone,
  openSpawnedFoodCrate,
  openSpawnedLegendaryCrate,
  pickupSpawnedCore,
} from './spawnConsumersRuntime';
import {
  buildRuntimeSpawnMeta,
  expandMissingResourceChain,
  pickGoalResourceZoneTargets,
} from './resourceTargetingRuntime';
import {
  bfsNextStepToAnyTarget,
  bfsPickSafestZone,
} from './pathfindingRuntime';
import {
  ensureWorldSpawns,
} from './worldSpawnRuntime';
import {
  autoEquipBest,
  computeLateGameUpgradeNeed,
  countLowMaterials,
  consumeLowMaterials,
  day1HeroGearDirector,
  ensureRoomForEquipment,
  findInvItemIdBySpecialKind,
  getInvId,
  getInvTier,
  invHasSpecialKind,
  isLowMaterialInvEntry,
  lateGameGearDirector,
  tryAutoCraftFromInventory,
  tryImmediateCraftFromSpecial,
} from './gearDirectorRuntime';
import {
  chooseAiMoveTargets,
  lowestEquippedTier,
  pickMissingBasicItemId,
  rollDroneOrder,
  rollKioskInteraction,
} from './aiEconomyRuntime';
import {
  pickAutoTranscendOption,
  rollFieldLoot,
  rollTranscendPickOptions,
} from './fieldLootRuntime';
import {
  applyAiRecoveryWindow,
  clearRuntimeCombatFields,
  isAiRecoveryLocked,
  normalizeDeadSnapshot,
  normalizeRevivedSurvivor,
  pickUnitsFromInventory,
  pruneEquippedAgainstInventory,
  removePickedUnitsFromInventory,
} from './survivorLifecycleRuntime';
import {
  MAT_FORCE_CORE_ID,
  MAT_METEOR_ID,
  MAT_TREE_ID,
  invDecOne,
  invHasOne,
  invKey,
  makeForceCore,
  tryAutoCraftForceCore,
} from './forceCoreRuntime';
import {
  safeGenerateDynamicEvent,
} from './dynamicEventRuntime';
import {
  areSameTeam,
  assignSimulationTeams,
  getActorTeamId,
  getActorTeamName,
  getAliveTeams,
  getWinningTeam,
  pickTeamRepresentative,
} from './teamRuntime';

export {
  safeTags,
  itemDisplayName,
  resolveRewardDropEntry,
  normalizeRewardDropEntries,
  itemIcon,
  shuffleArray,
  EQUIP_SLOTS,
  START_WEAPON_TYPES,
  INIT_DEPENDENCY_PATHS,
  normalizeUserStatistics,
  mergeStoredUserProgress,
  PERK_EFFECT_DEFAULTS,
  PERK_EFFECT_ALIASES,
  perkNumber,
  normalizePerkPct,
  normalizePerkEffects,
  buildPerkRuntimeBundle,
  getActorPerkEffects,
  applyPerkDiscount,
  getPerkLootBias,
  getPerkAggressionBias,
  applyPerkLootWeight,
  getPerkWildlifeLootBias,
  getPerkEventItemBias,
  applyPerkCreditBonus,
  applyPerkDamageReduction,
  maybeBoostDropQty,
  applyPerkBundleToActor,
  ensureEquipped,
  normalizeRuntimeInventory,
  normalizeRuntimeEffect,
  normalizeRuntimeSurvivorList,
  buildRuntimeSurvivorMap,
  upsertRuntimeSurvivor,
  normalizeRuntimeSurvivor,
  getInvItemId,
  getSimEquipExternalId,
  isSimGeneratedEquipment,
  getEquipMoveSpeed,
  SLOT_ICON,
  LUMIA_ZONE_POS,
  LUMIA_DEFAULT_EDGES,
  shortText,
  hash32,
  extractActorNameFromLog,
  getEquipSummary,
  compactIO,
  isEnabledScenarioEvent,
  getScenarioEventTimeOfDay,
  localKeyHyperloops,
  localKeyHyperloopDeviceZone,
  readLocalJsonArray,
  uniqStr,
  randInt,
  pickWeighted,
  clampTier4,
  tierLabelKo,
  crateTypeLabel,
  rollTranscendPickOptions,
  pickAutoTranscendOption,
  rollFieldLoot,
  normalizeMatchKey,
  findItemByKeywords,
  getEquipTierSummary,
  getLegendaryCoreCandidates,
  resolveLegendaryDropWeights,
  rollLegendaryCrateLoot,
  pickFromAllCrates,
  pickUnitsFromInventory,
  removePickedUnitsFromInventory,
  pruneEquippedAgainstInventory,
  clearRuntimeCombatFields,
  applyAiRecoveryWindow,
  isAiRecoveryLocked,
  normalizeDeadSnapshot,
  normalizeRevivedSurvivor,
  applyStatusEffect,
  clearNegativeStatusEffects,
  applyShieldEffect,
  applyRegenEffect,
  describeRuntimeEffect,
  applyRuntimeEffectPayloads,
  consumeShieldDamage,
  clearPostCombatEffects,
  countInventoryUnits,
  kioskLegendaryPrice,
  zoneNameHasKiosk,
  hasKioskAtZone,
  canUseKioskAtWorldTime,
  createInitialSpawnState,
  cloneSpawnState,
  zoneHasKioskFlag,
  getEligibleSpawnZoneIds,
  LEGACY_CORE_ZONE_IDS,
  LEGACY_CORE_ZONE_NAME_KEYS,
  zoneAllowsNaturalCore,
  getEligibleCoreSpawnZoneIds,
  localKeyMutantWildlifeZone,
  readLocalString,
  getMutantWildlifeSpawnZoneId,
  getHyperloopDeviceZoneId,
  ensureWorldSpawns,
  openSpawnedLegendaryCrate,
  openSpawnedFoodCrate,
  pickupSpawnedCore,
  consumeBossAtZone,
  consumeMutantWildlifeAtZone,
  classifySpecialByName,
  isSpecialCoreKind,
  computeCraftTierFromIngredients,
  applyEquipTier,
  isItemInMapCrates,
  normalizeGoalTier,
  pickGoalLoadoutBySlot,
  pickGoalLoadoutKeys,
  getOneSpecialShortMissing,
  buildCraftGoal,
  uniqStrings,
  listKioskZoneIdsForMap,
  findCrateZoneIdsForItem,
  findCrateZoneWeightsForItem,
  buildRuntimeSpawnMeta,
  expandMissingResourceChain,
  pickGoalResourceZoneTargets,
  bfsNextStepToAnyTarget,
  bfsPickSafestZone,
  invHasSpecialKind,
  findInvItemIdBySpecialKind,
  computeLateGameUpgradeNeed,
  chooseAiMoveTargets,
  pickMissingBasicItemId,
  rollKioskInteraction,
  lowestEquippedTier,
  rollDroneOrder,
  readStat,
  roughPower,
  rollWildlifeEncounter,
  consumeWildlifeAtZone,
  rollNaturalCoreSpawn,
  DEFAULT_INV_RULES,
  getInvRules,
  inferItemCategory,
  inferEquipSlot,
  getEffectIndex,
  hasActiveEffect,
  removeActiveEffect,
  isBandageLikeItem,
  canReceiveItem,
  normalizeInventory,
  formatInvRuleState,
  formatInvAddNote,
  addItemToInventory,
  invQty,
  consumeIngredientsFromInv,
  tryAutoCraftFromLoot,
  buildCraftDebugInfo,
  tryAutoCraftFromInventory,
  getInvId,
  getInvTier,
  isLowMaterialInvEntry,
  countLowMaterials,
  consumeLowMaterials,
  pickBestEquipBySlot,
  autoEquipBest,
  day1HeroGearDirector,
  lateGameGearDirector,
  ensureRoomForEquipment,
  tryImmediateCraftFromSpecial,
  MAT_METEOR_ID,
  MAT_TREE_ID,
  MAT_FORCE_CORE_ID,
  invKey,
  invDecOne,
  invHasOne,
  makeForceCore,
  tryAutoCraftForceCore,
  safeGenerateDynamicEvent,
  areSameTeam,
  assignSimulationTeams,
  getActorTeamId,
  getActorTeamName,
  getAliveTeams,
  getWinningTeam,
  pickTeamRepresentative,
  getTimeOfDayFromPhase,
  worldTimeText,
  isAtOrAfterWorldTime,
  worldPhaseIndex,
  saveLocalHallOfFameBackup,
};
