export const EQUIP_SLOTS = ['weapon', 'head', 'clothes', 'arm', 'shoes'];

export const START_WEAPON_TYPES = [
  '권총', '돌격소총', '돌소총', '저격총', '장갑', '톤파', '쌍절곤', '아르카나', '검', '쌍검', '망치',
  '방망이', '채찍', '투척', '암기', '활', '석궁', '도끼', '단검', '창', '레이피어',
];

export const INIT_DEPENDENCY_PATHS = [
  '/characters',
  '/events',
  '/settings',
  '/user/me',
  '/public/items',
  '/public/maps',
  '/public/kiosks',
  '/public/drone-offers',
  '/public/perks',
  '/trades',
  '/trades?mine=true',
];

export const SLOT_ICON = { weapon: '⚔️', head: '🪖', clothes: '👕', arm: '🦾', shoes: '👟' };

export const LUMIA_ZONE_POS = {
  gas_station: { x: 31, y: 12 },
  alley: { x: 49, y: 6 },
  archery: { x: 14, y: 27 },
  school: { x: 31, y: 40 },
  police: { x: 57, y: 27 },
  firestation: { x: 48, y: 41 },
  temple: { x: 78, y: 25 },
  stream: { x: 75, y: 39 },
  park: { x: 59, y: 52 },
  hospital: { x: 86, y: 50 },
  hotel: { x: 8, y: 43 },
  beach: { x: 18, y: 56 },
  forest: { x: 32, y: 56 },
  apartment: { x: 20, y: 76 },
  cemetery: { x: 64, y: 62 },
  cathedral: { x: 50, y: 77 },
  warehouse: { x: 35, y: 90 },
  port: { x: 52, y: 95 },
  barge: { x: 64, y: 96 },
  factory: { x: 79, y: 82 },
  lab: { x: 45, y: 50 },
  pond: { x: 59, y: 52 },
  residential: { x: 20, y: 76 },
};

export const LUMIA_DEFAULT_EDGES = [
  ['alley', 'gas_station'],
  ['alley', 'police'],
  ['alley', 'temple'],
  ['gas_station', 'archery'],
  ['gas_station', 'school'],
  ['gas_station', 'firestation'],
  ['archery', 'school'],
  ['archery', 'hotel'],
  ['school', 'firestation'],
  ['school', 'hotel'],
  ['school', 'forest'],
  ['school', 'lab'],
  ['police', 'temple'],
  ['police', 'firestation'],
  ['police', 'stream'],
  ['firestation', 'park'],
  ['firestation', 'lab'],
  ['temple', 'stream'],
  ['stream', 'park'],
  ['stream', 'hospital'],
  ['park', 'hospital'],
  ['park', 'cemetery'],
  ['hospital', 'cemetery'],
  ['hospital', 'factory'],
  ['hotel', 'beach'],
  ['hotel', 'forest'],
  ['beach', 'forest'],
  ['beach', 'apartment'],
  ['forest', 'apartment'],
  ['forest', 'cathedral'],
  ['forest', 'lab'],
  ['apartment', 'warehouse'],
  ['apartment', 'cathedral'],
  ['cemetery', 'cathedral'],
  ['cemetery', 'factory'],
  ['cemetery', 'lab'],
  ['cathedral', 'warehouse'],
  ['cathedral', 'factory'],
  ['cathedral', 'port'],
  ['warehouse', 'port'],
  ['port', 'barge'],
  ['port', 'factory'],
  ['barge', 'factory'],
];
