export const EQUIP_SLOTS = ['weapon', 'head', 'clothes', 'arm', 'shoes'];

export const START_WEAPON_TYPES = [
  '권총', '돌격소총', '돌소총', '저격총', '장갑', '톤파', '쌍절곤', '아르카나', '검', '쌍검', '망치',
  '방망이', '채찍', '투척', '암기', '활', '석궁', '도끼', '단검', '창', '레이피어',
];

export const INIT_DEPENDENCY_PATHS = [
  '/characters',
  '/events',
  '/settings',
  '/user/me',
  '/public/items',
  '/public/maps',
  '/public/kiosks',
  '/public/drone-offers',
  '/public/perks',
  '/trades',
  '/trades?mine=true',
];

export const SLOT_ICON = { weapon: '⚔️', head: '🪖', clothes: '👕', arm: '🦾', shoes: '👟' };

export const LUMIA_ZONE_POS = {
  alley: { x: 26, y: 24 },
  gas_station: { x: 39, y: 19 },
  archery: { x: 52, y: 16 },
  school: { x: 58, y: 28 },
  police: { x: 25, y: 39 },
  firestation: { x: 43, y: 37 },
  temple: { x: 16, y: 52 },
  stream: { x: 28, y: 58 },
  park: { x: 42, y: 59 },
  hospital: { x: 51, y: 68 },
  hotel: { x: 70, y: 24 },
  beach: { x: 84, y: 31 },
  forest: { x: 71, y: 45 },
  sandy_beach: { x: 84, y: 53 },
  apartment: { x: 76, y: 66 },
  cemetery: { x: 55, y: 52 },
  cathedral: { x: 66, y: 72 },
  warehouse: { x: 79, y: 80 },
  port: { x: 72, y: 91 },
  barge: { x: 58, y: 92 },
  factory: { x: 51, y: 82 },
  lab: { x: 59, y: 40 },
};

export const LUMIA_DEFAULT_EDGES = [
  ['alley', 'gas_station'],
  ['alley', 'police'],
  ['alley', 'temple'],
  ['gas_station', 'archery'],
  ['gas_station', 'school'],
  ['gas_station', 'firestation'],
  ['archery', 'school'],
  ['archery', 'hotel'],
  ['school', 'firestation'],
  ['school', 'hotel'],
  ['school', 'forest'],
  ['school', 'lab'],
  ['police', 'temple'],
  ['police', 'firestation'],
  ['police', 'stream'],
  ['firestation', 'park'],
  ['firestation', 'lab'],
  ['temple', 'stream'],
  ['stream', 'park'],
  ['stream', 'hospital'],
  ['park', 'hospital'],
  ['park', 'cemetery'],
  ['hospital', 'cemetery'],
  ['hospital', 'factory'],
  ['hotel', 'beach'],
  ['hotel', 'forest'],
  ['beach', 'forest'],
  ['beach', 'apartment'],
  ['forest', 'sandy_beach'],
  ['forest', 'apartment'],
  ['forest', 'cathedral'],
  ['forest', 'lab'],
  ['apartment', 'sandy_beach'],
  ['apartment', 'warehouse'],
  ['apartment', 'cathedral'],
  ['cemetery', 'cathedral'],
  ['cemetery', 'factory'],
  ['cemetery', 'lab'],
  ['cathedral', 'warehouse'],
  ['cathedral', 'factory'],
  ['cathedral', 'port'],
  ['warehouse', 'port'],
  ['port', 'barge'],
  ['port', 'factory'],
  ['barge', 'factory'],
];
