import { createPhaseDeathRuntime } from './phaseDeathRuntime';
import { finalizeSimulationPhase } from './phaseFinalizationRuntime';
import { runPvpActionLoop } from './phasePvpActionLoopRuntime';
import { runPhaseActorActionPipeline } from './phaseActorActionPipelineRuntime';
import { runSimulationPhaseSetup } from './simulationPhaseSetupRuntime';
import { runPhaseWorldResolution } from './phaseWorldResolutionRuntime';

const HYPERLOOP_DELAY_SEC = 3;

export async function runSimulationPhaseCycle({
  actions = {},
  helpers = {},
  refs = {},
  state = {},
} = {}) {
  const {
    activeMapIdRef,
    activeMapRef,
    autoSpeedRef,
    fullLogEntriesRef,
    startStarterLoadoutAppliedRef,
    suddenDeathActiveRef,
    suddenDeathEndAtSecRef,
    suddenDeathForbiddenAnnouncedRef,
  } = refs;
  const {
    activeMap,
    activeMapId,
    assistCounts,
    autoSpeed,
    craftables,
    day,
    dead,
    droneOffers,
    itemKeyById,
    itemMetaById,
    itemNameById,
    kiosks,
    killCounts,
    matchSec,
    pendingTranscendPick,
    phase,
    publicItems,
    selectedCharId,
    settings,
    showMarketPanel,
    spawnState,
    survivors,
    zoneGraph,
    zones,
  } = state;
  const {
    getForbiddenAddedZoneIdsForPhase,
    getForbiddenZoneIdsForPhase,
    getZoneName,
    isHyperloopTransit,
  } = helpers;
  const {
    addLog,
    applyErTraitAfterBattle,
    applyErWeaponSkillAfterCombat,
    applyLootCraftResult,
    applyUserEconomyProgress,
    emitConsumableRunEvent,
    emitCraftRunEvent,
    emitEffectRunEvents,
    emitItemGainIfAny,
    emitObjectiveRunEvent,
    emitQueueRunEvent,
    emitRunEvent,
    finishGame,
    grantMasteries,
    grantMastery,
    grantPvpDamageMastery,
    grantPvpKillMastery,
    normalizeAutoSpeed,
    persistSimEquipmentsFromChars,
    resetPhaseLogs,
    setAssistCounts,
    setDay,
    setDead,
    setForbiddenAddedNow,
    setKillCounts,
    setMatchSec,
    setPendingTranscendPick,
    setPhase,
    setSpawnState,
    setSurvivors,
  } = actions;

  const {
    atNow,
    baseCredits,
    battleSettings,
    canReviveThisMatch,
    currentActionSec,
    damagePerTick,
    fogLocalSec,
    forbiddenIds,
    getPhaseRuntimeOffsetSec,
    isSoloMatch,
    mapObj,
    marketRules,
    nextDay,
    nextPhase,
    nextSpawn,
    phaseDurationSec,
    phaseIdxNow,
    phaseStartSec,
    phaseSurvivors,
    reserveActionSecond,
    reserveVisibleSecond,
    reviveCutoffIdx,
    ruleset,
    runVisibleClockToPhaseEnd,
    suddenDeathSafeZoneIds,
    tickSec,
    useDetonation,
    wipeProtectionCutoffIdx,
  } = runSimulationPhaseSetup({
    actions,
    helpers,
    refs,
    state,
  });
  let earnedCredits = baseCredits;
  let pendingPickAssigned = false;

  const newlyDead = [];
  const phaseDeathLogStartIndex = Array.isArray(fullLogEntriesRef.current) ? fullLogEntriesRef.current.length : 0;
  const {
    appendPhaseDeadSnapshots,
    emitDeathRunEventOnce,
    flushDeadSnapshots,
    phaseDeadSnapshots,
    reconcileZeroHpDeaths,
    setDeathMetadata,
  } = createPhaseDeathRuntime({
    addLog,
    atNow,
    currentActionSec,
    emitRunEvent,
    fullLogEntriesRef,
    phaseDeathLogStartIndex,
    phaseIdxNow,
    ruleset,
    setDead,
  });
  const movePowerContext = { ruleset, battleSettings };
  const actorActionPipelineResult = runPhaseActorActionPipeline({
    state: {
      canReviveThisMatch,
      craftables,
      currentActionSec,
      damagePerTick,
      droneOffers,
      forbiddenIds,
      hyperloopDelaySec: HYPERLOOP_DELAY_SEC,
      isSoloMatch,
      itemKeyById,
      itemMetaById,
      itemNameById,
      kiosks,
      mapObj,
      marketRules,
      movePowerContext,
      nextDay,
      nextPhase,
      nextSpawn,
      pendingPickAssigned,
      pendingTranscendPick,
      phaseDurationSec,
      phaseIdxNow,
      phaseSurvivors,
      publicItems,
      reviveCutoffIdx,
      ruleset,
      selectedCharId,
      showMarketPanel,
      useDetonation,
      zoneGraph,
      zones,
    },
    actions: {
      addLog,
      applyLootCraftResult,
      atNow,
      emitCraftRunEvent,
      emitDeathRunEventOnce,
      emitItemGainIfAny,
      emitObjectiveRunEvent,
      emitQueueRunEvent,
      emitRunEvent,
      getZoneName,
      grantMastery,
      grantMasteries,
      isHyperloopTransit,
      reserveActionSecond,
      setDeathMetadata,
      setPendingTranscendPick,
    },
  });
  pendingPickAssigned = actorActionPipelineResult.pendingPickAssigned;
  if (Array.isArray(actorActionPipelineResult.newlyDead) && actorActionPipelineResult.newlyDead.length) {
    newlyDead.push(...actorActionPipelineResult.newlyDead);
  }
  let updatedSurvivors = Array.isArray(actorActionPipelineResult.updatedSurvivors)
    ? actorActionPipelineResult.updatedSurvivors
    : [];

  const worldResolutionResult = runPhaseWorldResolution({
    refs: {
      suddenDeathActiveRef,
    },
    state: {
      canReviveThisMatch,
      currentActionSec,
      fogLocalSec,
      forbiddenIds,
      isSoloMatch,
      itemMetaById,
      itemNameById,
      mapObj,
      movePowerContext,
      newlyDead,
      nextDay,
      nextPhase,
      nextSpawn,
      phaseDurationSec,
      phaseIdxNow,
      phaseStartSec,
      publicItems,
      reviveCutoffIdx,
      ruleset,
      suddenDeathSafeZoneIds,
      tickSec,
      updatedSurvivors,
      useDetonation,
      zoneGraph,
      zones,
    },
    actions: {
      addLog,
      appendPhaseDeadSnapshots,
      atNow,
      emitDeathRunEventOnce,
      emitItemGainIfAny,
      emitRunEvent,
      flushDeadSnapshots,
      getZoneName,
      setDeathMetadata,
    },
  });
  updatedSurvivors = worldResolutionResult.updatedSurvivors;
  const pvpActionLoopResult = await runPvpActionLoop({
    state: {
      battleSettings,
      canReviveThisMatch,
      craftables,
      currentActionSec,
      fogLocalSec,
      forbiddenIds,
      getPhaseRuntimeOffsetSec,
      isSoloMatch,
      itemMetaById,
      itemNameById,
      mapObj,
      nextDay,
      nextPhase,
      phaseDurationSec,
      phaseIdxNow,
      phaseSurvivors: updatedSurvivors,
      publicItems,
      reviveCutoffIdx,
      ruleset,
      tickSec,
      updatedSurvivors,
      useDetonation,
      zoneGraph,
    },
    actions: {
      addEarnedCredits: (amount) => {
        earnedCredits += Math.max(0, Number(amount || 0));
      },
      addLog,
      appendPhaseDeadSnapshots,
      applyErTraitAfterBattle,
      applyErWeaponSkillAfterCombat,
      atNow,
      emitConsumableRunEvent,
      emitDeathRunEventOnce,
      emitEffectRunEvents,
      emitRunEvent,
      flushDeadSnapshots,
      getZoneName,
      grantPvpDamageMastery,
      grantPvpKillMastery,
      reserveActionSecond,
      reserveVisibleSecond,
      setDeathMetadata,
    },
  });
  const {
    estimatePower,
    newDeadIds,
    roundAssists,
    roundKills,
    survivorMap,
  } = pvpActionLoopResult;
  const phaseFinalizationResult = await finalizeSimulationPhase({
    refs: {
      suddenDeathActiveRef,
      suddenDeathEndAtSecRef,
    },
    state: {
      assistCounts,
      baseCredits,
      canReviveThisMatch,
      dead,
      earnedCredits,
      estimatePower,
      getPhaseRuntimeOffsetSec,
      isSoloMatch,
      killCounts,
      matchSec,
      newDeadIds,
      nextDay,
      nextPhase,
      nextSpawn,
      phaseDeadSnapshots,
      phaseDurationSec,
      phaseIdxNow,
      phaseStartSec,
      reviveCutoffIdx,
      wipeProtectionCutoffIdx,
      roundAssists,
      roundKills,
      ruleset,
      survivorMap,
    },
    actions: {
      addLog,
      appendPhaseDeadSnapshots,
      applyUserEconomyProgress,
      emitDeathRunEventOnce,
      finishGame,
      flushDeadSnapshots,
      persistSimEquipmentsFromChars,
      reconcileZeroHpDeaths,
      runVisibleClockToPhaseEnd,
      setAssistCounts,
      setDeathMetadata,
      setKillCounts,
      setMatchSec,
      setSpawnState,
      setSurvivors,
    },
  });
  if (phaseFinalizationResult?.shouldReturn) return;
}
