export const VSCO2_CE_MINI_LIBRARY = Object.freeze({
  name: 'VS Chamber Orchestra 2 Community Edition - 50 Sample Pack',
  shortName: 'VSCO 2 CE Mini',
  version: '2.1.1',
  license: 'CC0-1.0',
  sourcePage: 'https://versilian-studios.com/vsco-community/',
  sourceArchive: 'https://s3.amazonaws.com/VersilianStudios/50OrchestralSamples.rar',
  sampleRate: 22_050,
});

export const VSCO2_CE_MINI_FILES = Object.freeze([
  '7TbnEns_Stac_Bb2_ff_1.wav',
  '7TbnEns_Stac_Bb2_mf_2.wav',
  '7TbnEns_Sus_Bb2_fff.wav',
  '7TbnEns_Sus_Bb3_fff.wav',
  'CelloEns_spic_C1_v2_5.wav',
  'CelloEns_spic_C3_v2_4.wav',
  'CelloEns_susvib_C1_v1_1.wav',
  'CelloEns_susvib_C3_v1_1.wav',
  'cymbal_crash1_ff3.wav',
  'cymbal_crash2_fff1.wav',
  'Euph1_vib-solo_A#2_v1_1.wav',
  'glock_medium_C6_01.wav',
  'gong_2_f.wav',
  'KHOboe_stac_Ab4_ff2.wav',
  'KHOboe_stac_Bb3_ff2.wav',
  'KHOboe_stac_D4_ff2.wav',
  'KHOboe_vib_Ab4_ff1.wav',
  'KHOboe_vib_Ab5_ff1.wav',
  'KHOboe_vib_D5_ff1.wav',
  'KSHarp_A2_f1.wav',
  'KSHarp_A4_mf1.wav',
  'LDFlute_expvib_A3_v1_1.wav',
  'LDFlute_expvib_A4_v1_1.wav',
  'LDFlute_expvib_D4_v1_1.wav',
  'LDFlute_trillW_C4_v1_1.wav',
  'LLVln_ArcoVib_A3_mf.wav',
  'LLVln_ArcoVib_A4_mf.wav',
  'LLVln_ArcoVib_A5_mf.wav',
  'Marimba_hit_Outrigger_C4_loud_01.wav',
  'Marimba_hit_Outrigger_G2_loud_01.wav',
  'piccolo_C5_sustain1.wav',
  'piccolo_C6_sustain1.wav',
  'PSBassoon_A#0_v2_2.wav',
  'PSBassoon_A#1_v2_2.wav',
  'snare3_f_1.wav',
  'snareNew_hit_fff1.wav',
  'snareNew_roll_fff1.wav',
  'susCymb1_cresc_4s.wav',
  'susCymb2_bowed_1.wav',
  'TB_hit_A4_v4_1.wav',
  'TB_hit_F5_v2_2.wav',
  'timpani_2_hit_ff2.wav',
  'timpani_3_hit_fff4.wav',
  'trem_C3_v1_1.wav',
  'trem_F4_v1_1.wav',
  'trumpet_loud_F5_1.wav',
  'Tuba1_Stac_Bb1_f2.wav',
  'Tuba2_sus_A#0_v3_1.wav',
  'Tuba2_sus_A#1_v3_1.wav',
  'Xylo_Medium_G4_ff_01_far.wav',
]);
