export const GAME_SLUG = 'ba-srpg';
export const QUICK_SAVE_SLOT = 'ba-srpg-main';
export const SAVE_VERSION = 'ba-srpg-v1';

export const GRID = { width: 8, height: 6 };
export const COVER_MAX_HP = 8;

export const ITEMS = [
  { id: 'mat_wood', name: '나무', kind: 'material', stackMax: 99 },
  { id: 'mat_stone', name: '돌', kind: 'material', stackMax: 99 },
  { id: 'con_bandage', name: '붕대', kind: 'consumable', stackMax: 20 },
  { id: 'eq_knife', name: '나이프', kind: 'equipment', stackMax: 1, stats: { atk: 2, acc: 5 } },
];

export const MISSIONS = [
  {
    id: 'm001',
    name: '첫 임무: 정찰',
    region: '학원구 외곽',
    objective: '학원구 외곽을 정찰하고 수상한 흔적을 기록한 뒤 귀환하십시오.',
    caution: '가벼운 교전 가능성. 엄폐를 활용하고 붕대를 준비하세요.',
    difficulty: 'easy',
    recommendedPower: 60,
    creditMin: 12,
    creditMax: 18,
    rewards: [
      { itemId: 'mat_wood', qtyMin: 1, qtyMax: 3, chance: 1 },
      { itemId: 'con_bandage', qtyMin: 1, qtyMax: 1, chance: 0.3 },
    ],
    enemies: [
      { id: 'e_scout', name: '정찰 드론', x: 5, y: 1, hp: 20, atk: 6, def: 1, range: 3, move: 2 },
      { id: 'e_raider', name: '소형 강습병', x: 6, y: 3, hp: 28, atk: 8, def: 2, range: 1, move: 2 },
    ],
  },
  {
    id: 'm002',
    name: '두번째 임무: 교전',
    region: '폐허 지구',
    objective: '폐허 지구에서 적을 격퇴하고 보급 상자를 확보하십시오.',
    caution: '적 사격이 거셀 수 있습니다. 이동 후 공격 각을 확보하세요.',
    difficulty: 'normal',
    recommendedPower: 120,
    creditMin: 18,
    creditMax: 28,
    rewards: [
      { itemId: 'mat_stone', qtyMin: 1, qtyMax: 3, chance: 1 },
      { itemId: 'con_bandage', qtyMin: 1, qtyMax: 1, chance: 0.3 },
    ],
    enemies: [
      { id: 'e_raider_a', name: '강습병 A', x: 5, y: 1, hp: 32, atk: 9, def: 2, range: 1, move: 2 },
      { id: 'e_raider_b', name: '강습병 B', x: 6, y: 4, hp: 32, atk: 9, def: 2, range: 1, move: 2 },
      { id: 'e_sniper', name: '폐허 저격수', x: 7, y: 2, hp: 24, atk: 10, def: 1, range: 4, move: 1 },
    ],
  },
  {
    id: 'm003',
    name: '세번째 임무: 보급로 확보',
    region: '보급로',
    objective: '상가-학원구 사이 보급로를 순찰하고 장애물을 제거한 뒤 보고하십시오.',
    caution: '소규모 매복 가능성. 이동 경로를 분산하고 엄폐를 끼고 접근하세요.',
    difficulty: 'easy',
    recommendedPower: 90,
    creditMin: 14,
    creditMax: 22,
    rewards: [
      { itemId: 'mat_wood', qtyMin: 2, qtyMax: 5, chance: 1 },
      { itemId: 'mat_stone', qtyMin: 1, qtyMax: 2, chance: 0.6 },
      { itemId: 'con_bandage', qtyMin: 1, qtyMax: 1, chance: 0.35 },
    ],
    enemies: [
      { id: 'e_blocker', name: '장애물 경비병', x: 5, y: 2, hp: 35, atk: 8, def: 3, range: 1, move: 1 },
      { id: 'e_runner', name: '우회조', x: 6, y: 0, hp: 24, atk: 7, def: 1, range: 2, move: 3 },
      { id: 'e_drone', name: '감시 드론', x: 7, y: 4, hp: 22, atk: 6, def: 1, range: 3, move: 2 },
    ],
  },
  {
    id: 'm004',
    name: '네번째 임무: 야전 진지',
    chapter: 1,
    region: '폐허 지구 외곽',
    objective: '폐허 지구 외곽의 야전 진지를 정리하고 남은 물자를 확보하십시오.',
    caution: '교전 강도가 상승합니다. 공격 각과 사거리(명중)를 먼저 확보하세요.',
    difficulty: 'normal',
    recommendedPower: 170,
    creditMin: 22,
    creditMax: 36,
    rewards: [
      { itemId: 'mat_stone', qtyMin: 2, qtyMax: 5, chance: 1 },
      { itemId: 'mat_wood', qtyMin: 1, qtyMax: 3, chance: 0.7 },
      { itemId: 'con_bandage', qtyMin: 1, qtyMax: 2, chance: 0.45 },
      { itemId: 'eq_knife', qtyMin: 1, qtyMax: 1, chance: 0.12 },
    ],
    enemies: [
      { id: 'e_vanguard', name: '야전 선봉병', x: 5, y: 1, hp: 38, atk: 10, def: 3, range: 1, move: 2 },
      { id: 'e_marksman', name: '야전 저격수', x: 7, y: 2, hp: 28, atk: 12, def: 1, range: 4, move: 1 },
      { id: 'e_guard', name: '보급 경비병', x: 6, y: 4, hp: 42, atk: 9, def: 4, range: 1, move: 1 },
      { id: 'e_drone_b', name: '감시 드론 B', x: 7, y: 0, hp: 24, atk: 7, def: 1, range: 3, move: 2 },
    ],
  },
  {
    id: 'm005',
    name: 'Hard 임무: 연구동 진입로',
    chapter: 2,
    region: '연구동 진입로',
    objective: '연구동 진입로의 경비망을 돌파하고 내부 침입로를 확보하십시오.',
    caution: 'Hard 임무입니다. 적 체력과 공격력이 상승하며, 엄폐를 빼앗기면 빠르게 무너집니다.',
    difficulty: 'hard',
    recommendedPower: 230,
    creditMin: 38,
    creditMax: 56,
    rewards: [
      { itemId: 'mat_stone', qtyMin: 3, qtyMax: 6, chance: 1 },
      { itemId: 'mat_wood', qtyMin: 2, qtyMax: 4, chance: 0.85 },
      { itemId: 'con_bandage', qtyMin: 1, qtyMax: 2, chance: 0.55 },
      { itemId: 'eq_knife', qtyMin: 1, qtyMax: 1, chance: 0.18 },
    ],
    enemies: [
      { id: 'e_hard_vanguard', name: '진입로 선봉대', x: 5, y: 1, hp: 48, atk: 12, def: 4, range: 1, move: 2 },
      { id: 'e_hard_shield', name: '방패 경비병', x: 6, y: 3, hp: 58, atk: 10, def: 6, range: 1, move: 1 },
      { id: 'e_hard_marksman', name: '고지 저격수', x: 7, y: 0, hp: 32, atk: 14, def: 2, range: 4, move: 1 },
      { id: 'e_hard_drone', name: '전술 드론', x: 7, y: 5, hp: 30, atk: 9, def: 2, range: 3, move: 3 },
    ],
  },
  {
    id: 'm006',
    name: 'VeryHard 임무: 연구동 심부',
    chapter: 2,
    region: '연구동 심부',
    objective: '심부 제어실을 장악한 경비장을 쓰러뜨리고 연구동 자료를 회수하십시오.',
    caution: 'VeryHard 임무입니다. 보스 화력이 높고 빠른 클리어 턴 조건이 빡빡합니다.',
    difficulty: 'veryhard',
    recommendedPower: 320,
    creditMin: 62,
    creditMax: 88,
    rewards: [
      { itemId: 'mat_stone', qtyMin: 4, qtyMax: 8, chance: 1 },
      { itemId: 'mat_wood', qtyMin: 3, qtyMax: 6, chance: 0.9 },
      { itemId: 'con_bandage', qtyMin: 2, qtyMax: 3, chance: 0.65 },
      { itemId: 'eq_knife', qtyMin: 1, qtyMax: 1, chance: 0.28 },
    ],
    enemies: [
      { id: 'e_vh_guard_a', name: '심부 경비병 A', x: 5, y: 1, hp: 54, atk: 13, def: 5, range: 1, move: 2 },
      { id: 'e_vh_guard_b', name: '심부 경비병 B', x: 5, y: 4, hp: 54, atk: 13, def: 5, range: 1, move: 2 },
      { id: 'e_vh_sniper', name: '심부 저격수', x: 7, y: 0, hp: 38, atk: 16, def: 2, range: 4, move: 1 },
      { id: 'e_vh_boss', name: '연구동 경비장', x: 7, y: 3, hp: 92, atk: 15, def: 7, range: 3, move: 2 },
    ],
  },
  {
    id: 'm007',
    name: 'Chapter 3: 해안 보급기지',
    chapter: 3,
    region: '해안 보급기지',
    objective: '해안 보급기지의 장거리 포대를 제압하고 보급 차단선을 확보하십시오.',
    caution: '장거리 포대와 기동 정찰조가 함께 등장합니다. 엄폐와 돌격 각을 동시에 관리해야 합니다.',
    difficulty: 'hard',
    recommendedPower: 390,
    creditMin: 76,
    creditMax: 104,
    rewards: [
      { itemId: 'mat_stone', qtyMin: 5, qtyMax: 9, chance: 1 },
      { itemId: 'mat_wood', qtyMin: 4, qtyMax: 7, chance: 0.9 },
      { itemId: 'con_bandage', qtyMin: 2, qtyMax: 3, chance: 0.72 },
      { itemId: 'eq_knife', qtyMin: 1, qtyMax: 1, chance: 0.34 },
    ],
    enemies: [
      { id: 'e_c3_artillery', name: '해안 포대', x: 7, y: 1, hp: 64, atk: 17, def: 3, range: 5, move: 1 },
      { id: 'e_c3_runner_a', name: '기동 정찰조 A', x: 5, y: 0, hp: 42, atk: 12, def: 2, range: 2, move: 4 },
      { id: 'e_c3_runner_b', name: '기동 정찰조 B', x: 5, y: 5, hp: 42, atk: 12, def: 2, range: 2, move: 4 },
      { id: 'e_c3_guard', name: '보급기지 장갑병', x: 6, y: 3, hp: 70, atk: 12, def: 7, range: 1, move: 1 },
    ],
  },
  {
    id: 'm008',
    name: 'Chapter 3: 지휘 노드 탈환',
    chapter: 3,
    region: '지휘 노드',
    objective: '적 지휘 노드를 탈환하고 고화력 지휘 개체를 격파하십시오.',
    caution: '복합 패턴 보스전입니다. 저격수, 방패병, 보스 사격이 동시에 들어오므로 집중 화력이 필요합니다.',
    difficulty: 'veryhard',
    recommendedPower: 470,
    creditMin: 98,
    creditMax: 132,
    rewards: [
      { itemId: 'mat_stone', qtyMin: 6, qtyMax: 10, chance: 1 },
      { itemId: 'mat_wood', qtyMin: 5, qtyMax: 8, chance: 0.92 },
      { itemId: 'con_bandage', qtyMin: 2, qtyMax: 4, chance: 0.78 },
      { itemId: 'eq_knife', qtyMin: 1, qtyMax: 1, chance: 0.42 },
    ],
    enemies: [
      { id: 'e_c3_node_guard', name: '노드 방패병', x: 5, y: 2, hp: 78, atk: 13, def: 8, range: 1, move: 1 },
      { id: 'e_c3_node_sniper', name: '노드 저격수', x: 7, y: 0, hp: 46, atk: 18, def: 2, range: 5, move: 1 },
      { id: 'e_c3_node_drone', name: '교란 드론', x: 6, y: 5, hp: 48, atk: 11, def: 3, range: 3, move: 4 },
      { id: 'e_c3_commander', name: '지휘 노드 관리자', x: 7, y: 3, hp: 118, atk: 18, def: 7, range: 4, move: 2 },
    ],
  },
];

export const MISSION_OBJECTIVES = {
  m001: {
    id: 'recon-marker',
    label: '정찰 표식',
    detail: '적을 정리한 뒤 목표 칸에 학생을 이동시켜 정찰 기록을 확보하십시오.',
    x: 4,
    y: 0,
    action: 'srpg-objective-recon',
  },
  m002: {
    id: 'supply-crate',
    label: '보급 상자',
    detail: '폐허 끝의 보급 상자를 직접 확보해야 임무가 완료됩니다.',
    x: 6,
    y: 5,
    action: 'srpg-objective-supply',
  },
  m003: {
    id: 'route-beacon',
    label: '보급로 표지',
    detail: '교전 후 중앙 보급로 표지를 재가동하십시오.',
    x: 4,
    y: 3,
    action: 'srpg-objective-route',
  },
  m004: {
    id: 'field-cache',
    label: '야전 물자',
    detail: '진지 후방에 남은 야전 물자를 회수하십시오.',
    x: 6,
    y: 5,
    action: 'srpg-objective-supply',
  },
  m005: {
    id: 'breach-console',
    label: '침입 단말',
    detail: '경비망을 돌파하고 침입 단말에 학생을 배치하십시오.',
    x: 5,
    y: 4,
    action: 'srpg-objective-breach',
  },
  m006: {
    id: 'research-data',
    label: '연구 자료',
    detail: '경비장을 격파한 뒤 제어실 자료를 회수하십시오.',
    x: 6,
    y: 2,
    action: 'srpg-objective-data',
  },
  m007: {
    id: 'artillery-control',
    label: '포대 제어기',
    detail: '해안 포대를 무력화하고 제어기를 점령하십시오.',
    x: 6,
    y: 2,
    action: 'srpg-objective-artillery',
  },
  m008: {
    id: 'command-node',
    label: '지휘 노드',
    detail: '관리자를 격파하고 지휘 노드를 탈환하십시오.',
    x: 6,
    y: 4,
    action: 'srpg-objective-command',
  },
};

export const MISSION_EVENTS = {
  m001: [
    {
      id: 'sensor-smoke',
      turn: 2,
      kind: 'smoke',
      label: '센서 교란',
      detail: '중앙에 교란 연막이 전개되어 안팎 사격 명중률이 감소합니다.',
      x: 4,
      y: 2,
      radius: 1,
      duration: 2,
      accuracyMod: -0.18,
      action: 'srpg-event-smoke',
      cue: 'missionEventSmoke',
    },
  ],
  m002: [
    {
      id: 'ruin-reinforcement',
      turn: 2,
      kind: 'reinforcement',
      label: '폐허 증원',
      detail: '후방 통로에서 기동 증원 한 기가 진입합니다.',
      enemy: { id: 'e_event_runner', name: '폐허 기동병', x: 7, y: 5, hp: 26, atk: 8, def: 2, range: 2, move: 3 },
      action: 'srpg-event-reinforcement',
      cue: 'reinforcement',
    },
  ],
  m003: [
    {
      id: 'route-supply',
      turn: 2,
      kind: 'allySupply',
      label: '보급 드론 도착',
      detail: '보급 드론이 생존 학생의 HP와 보호막을 보충합니다.',
      heal: 8,
      shield: 5,
      duration: 2,
      action: 'srpg-event-supply',
      cue: 'missionEventSupply',
    },
  ],
  m004: [
    {
      id: 'field-command',
      turn: 2,
      kind: 'enemyBuff',
      label: '야전 사격 지시',
      detail: '적 지휘 신호로 생존 적의 명중률이 2턴 동안 상승합니다.',
      stat: 'Accuracy',
      add: 0.12,
      duration: 2,
      action: 'srpg-event-command',
      cue: 'missionEventCommand',
    },
  ],
  m005: [
    {
      id: 'corridor-collapse',
      turn: 2,
      kind: 'hazard',
      label: '통로 붕괴',
      detail: '붕괴 지점 주변의 학생이 파편 피해를 받습니다.',
      x: 4,
      y: 3,
      radius: 1,
      damage: 6,
      action: 'srpg-event-hazard',
      cue: 'missionEventHazard',
    },
  ],
  m006: [
    {
      id: 'deep-reinforcement',
      turn: 2,
      kind: 'reinforcement',
      label: '심부 경비 증원',
      detail: '제어실 남쪽에서 방패 증원이 진입합니다.',
      enemy: { id: 'e_event_deep_guard', name: '심부 증원병', x: 6, y: 5, hp: 48, atk: 12, def: 5, range: 1, move: 2 },
      action: 'srpg-event-reinforcement',
      cue: 'reinforcement',
    },
  ],
  m007: [
    {
      id: 'coastal-bombardment',
      turn: 2,
      kind: 'hazard',
      label: '해안 포격',
      detail: '중앙 작전 구역에 포격이 떨어져 반경 안 학생이 피해를 받습니다.',
      x: 4,
      y: 2,
      radius: 2,
      damage: 7,
      action: 'srpg-event-hazard',
      cue: 'missionEventHazard',
    },
  ],
  m008: [
    {
      id: 'node-lockdown',
      turn: 2,
      kind: 'enemyBuff',
      label: '노드 봉쇄',
      detail: '지휘 노드가 생존 적에게 방어 강화 신호를 전송합니다.',
      stat: 'Defense',
      add: 2,
      duration: 2,
      action: 'srpg-event-command',
      cue: 'missionEventCommand',
    },
  ],
};

export const ENEMY_PATTERNS = {
  targetLock: {
    id: 'targetLock',
    name: '표적 분석',
    kind: 'mark',
    interval: 2,
    range: 5,
    detail: '가장 가까운 학생의 회피를 낮춰 후속 사격 명중률을 높입니다.',
    action: 'srpg-enemy-mark',
    cue: 'enemyMark',
  },
  suppress: {
    id: 'suppress',
    name: '제압 사격',
    kind: 'suppress',
    interval: 3,
    range: 4,
    damageMul: 0.7,
    detail: '피해와 함께 혼란을 부여해 명중률을 낮춥니다.',
    action: 'srpg-enemy-suppress',
    cue: 'enemySuppress',
  },
  bulwark: {
    id: 'bulwark',
    name: '방벽 전개',
    kind: 'bulwark',
    interval: 2,
    range: 0,
    shield: 10,
    detail: '자신과 가까운 적에게 보호막을 부여합니다.',
    action: 'srpg-enemy-bulwark',
    cue: 'enemyBulwark',
  },
  barrage: {
    id: 'barrage',
    name: '집중 포격',
    kind: 'barrage',
    interval: 2,
    range: 6,
    radius: 1,
    damageMul: 0.8,
    detail: '표적과 인접한 학생에게 범위 피해를 줍니다.',
    action: 'srpg-enemy-barrage',
    cue: 'enemyBarrage',
  },
  command: {
    id: 'command',
    name: '전술 지휘',
    kind: 'command',
    interval: 3,
    range: 0,
    detail: '생존 적 전체의 명중률과 이동력을 강화합니다.',
    action: 'srpg-enemy-command',
    cue: 'enemyCommand',
  },
  assault: {
    id: 'assault',
    name: '돌파 강습',
    kind: 'assault',
    interval: 3,
    range: 1,
    damageMul: 1.25,
    detail: '근접 표적에게 강한 단일 피해를 줍니다.',
    action: 'srpg-enemy-assault',
    cue: 'enemyAssault',
  },
};

export const STUDENTS = [
  {
    id: 's_hoshino',
    name: '호시노',
    role: '탱커',
    x: 0,
    y: 2,
    hp: 54,
    atk: 10,
    def: 5,
    range: 1,
    move: 2,
    skillIds: ['sk_guard', 'sk_breach_shot', 'sk_overwatch'],
    tacticalProfile: '선봉에서 보호막으로 버티고 엄폐를 부순 뒤 오버워치로 진입로를 봉쇄합니다.',
  },
  {
    id: 's_yuuka',
    name: '유우카',
    role: '방어',
    x: 1,
    y: 3,
    hp: 46,
    atk: 8,
    def: 6,
    range: 1,
    move: 2,
    skillIds: ['sk_guard', 'sk_first_aid', 'sk_rally'],
    tacticalProfile: '방어 태세와 응급 처치에 사기 고양을 더해 전원 생존과 명중을 보조합니다.',
  },
  {
    id: 's_mika',
    name: '미카',
    role: '돌격',
    x: 0,
    y: 1,
    hp: 42,
    atk: 14,
    def: 3,
    range: 1,
    move: 3,
    skillIds: ['sk_dash_strike', 'sk_bleed_round', 'sk_suppress'],
    tacticalProfile: '돌파 일격으로 거리를 좁히고 출혈과 제압으로 보스의 행동 반경을 줄입니다.',
  },
  {
    id: 's_noa',
    name: '노아',
    role: '지원',
    x: 1,
    y: 2,
    hp: 34,
    atk: 7,
    def: 2,
    range: 3,
    move: 2,
    skillIds: ['sk_confuse_shot', 'sk_first_aid', 'sk_mark_target'],
    tacticalProfile: '교란과 표식으로 적의 명중·회피를 흔들고 빈 턴에는 회복을 담당합니다.',
  },
  {
    id: 's_hina',
    name: '히나',
    role: '화력',
    x: 0,
    y: 0,
    hp: 38,
    atk: 13,
    def: 3,
    range: 4,
    move: 2,
    skillIds: ['sk_burn_round', 'sk_precise_shot', 'sk_burst'],
    tacticalProfile: '원거리 화상과 점사로 고방어 적의 체력을 빠르게 깎습니다.',
  },
  {
    id: 's_shiroko',
    name: '시로코',
    role: '기동',
    x: 1,
    y: 1,
    hp: 40,
    atk: 11,
    def: 3,
    range: 3,
    move: 3,
    skillIds: ['sk_precise_shot', 'sk_smoke_grenade', 'sk_overwatch'],
    tacticalProfile: '기동 사격과 연막으로 교전 각을 바꾸고 오버워치로 추격을 차단합니다.',
  },
  {
    id: 's_serika',
    name: '세리카',
    role: '서포터',
    x: 1,
    y: 4,
    hp: 36,
    atk: 9,
    def: 3,
    range: 3,
    move: 3,
    skillIds: ['sk_first_aid', 'sk_bleed_round', 'sk_rally'],
    tacticalProfile: '회복과 출혈 압박을 오가며 사기 고양으로 장기전을 안정화합니다.',
  },
  {
    id: 's_iori',
    name: '이오리',
    role: '저격',
    x: 0,
    y: 5,
    hp: 35,
    atk: 12,
    def: 2,
    range: 5,
    move: 2,
    skillIds: ['sk_precise_shot', 'sk_grenade_flash', 'sk_breach_shot'],
    tacticalProfile: '긴 사거리의 섬광과 엄폐 파쇄탄으로 저격수·포대형 적을 먼저 끊습니다.',
  },
];

export const MAX_FORMATION_SIZE = 4;
export const DEFAULT_FORMATION_IDS = STUDENTS.slice(0, MAX_FORMATION_SIZE).map((student) => student.id);
export const FORMATION_SPAWNS = [
  { x: 0, y: 2 },
  { x: 1, y: 3 },
  { x: 0, y: 1 },
  { x: 1, y: 2 },
];

export const DIFFICULTY_RULES = {
  easy: { id: 'easy', label: 'Easy', hpMul: 1, atkMul: 1, rewardMul: 1, extraDropRolls: 0, targetTurn: 10 },
  normal: { id: 'normal', label: 'Normal', hpMul: 1, atkMul: 1, rewardMul: 1, extraDropRolls: 0, targetTurn: 11 },
  hard: { id: 'hard', label: 'Hard', hpMul: 1.15, atkMul: 1.1, rewardMul: 1.15, extraDropRolls: 1, targetTurn: 9 },
  veryhard: { id: 'veryhard', label: 'VeryHard', hpMul: 1.25, atkMul: 1.15, rewardMul: 1.3, extraDropRolls: 2, targetTurn: 8 },
};

export const STATUS_DEFS = {
  st_bleed: { id: 'st_bleed', name: '출혈', kind: 'DoT', tickDamage: 4, maxStacks: 1, merge: 'refresh' },
  st_burn: { id: 'st_burn', name: '화상', kind: 'DoT', tickDamage: 5, maxStacks: 2, merge: 'stackLimited' },
  st_stun: { id: 'st_stun', name: '기절', kind: 'Control', tickDamage: 0, maxStacks: 1, merge: 'extendOnly' },
  st_confuse: { id: 'st_confuse', name: '혼란', kind: 'Debuff', tickDamage: 0, maxStacks: 1, merge: 'refresh', accuracyMod: -0.2 },
};

export const TACTICAL_SKILLS = [
  {
    id: 'sk_guard',
    name: '방어 태세',
    action: 'guard',
    apCost: 2,
    target: 'self',
    rangeMin: 0,
    rangeMax: 0,
    shield: 8,
    duration: 2,
    desc: '자신에게 보호막 8을 부여합니다. 원본 Shield 정책처럼 수치는 합산하고 지속시간은 긴 쪽을 유지합니다.',
  },
  {
    id: 'sk_first_aid',
    name: '응급 처치',
    action: 'consume',
    apCost: 2,
    target: 'self',
    rangeMin: 0,
    rangeMax: 0,
    heal: 10,
    desc: '선택 학생의 HP를 10 회복합니다.',
  },
  {
    id: 'sk_precise_shot',
    name: '정밀 사격',
    action: 'attack',
    apCost: 2,
    target: 'enemy',
    rangeMin: 3,
    rangeMax: 7,
    damageMul: 1.2,
    accuracyAdd: 0.12,
    desc: '먼 거리에서 높은 명중률로 피해를 줍니다. 저격수와 포대형 적을 먼저 끊을 때 좋습니다.',
  },
  {
    id: 'sk_dash_strike',
    name: '돌파 일격',
    action: 'move',
    apCost: 2,
    target: 'enemy',
    rangeMin: 1,
    rangeMax: 2,
    damageMul: 1.35,
    accuracyAdd: 0.04,
    advance: 1,
    desc: '근거리 대상에게 강한 피해를 주고 빈 칸이 있으면 대상 쪽으로 1칸 전진합니다.',
  },
  {
    id: 'sk_bleed_round',
    name: '출혈탄',
    action: 'status',
    apCost: 2,
    target: 'enemy',
    rangeMin: 1,
    rangeMax: 4,
    damageMul: 1,
    statusId: 'st_bleed',
    statusChance: 0.85,
    duration: 2,
    accuracyAdd: 0,
    desc: '무기 피해를 주고 85% 확률로 출혈을 부여합니다.',
  },
  {
    id: 'sk_burn_round',
    name: '소이탄',
    action: 'status',
    apCost: 2,
    target: 'enemy',
    rangeMin: 1,
    rangeMax: 4,
    damageMul: 0.85,
    techDamage: true,
    statusId: 'st_burn',
    statusChance: 0.75,
    duration: 2,
    accuracyAdd: -0.04,
    desc: '기술 피해를 주고 75% 확률로 화상을 부여합니다. 화상은 최대 2중첩입니다.',
  },
  {
    id: 'sk_grenade_flash',
    name: '섬광 투척',
    action: 'status',
    apCost: 2,
    target: 'enemy',
    rangeMin: 1,
    rangeMax: 5,
    damageMul: 0,
    statusId: 'st_stun',
    statusChance: 0.6,
    duration: 1,
    radius: 1,
    accuracyAdd: 0.08,
    desc: '대상과 반경 1칸의 적에게 60% 확률로 기절을 부여합니다. 기절한 적은 다음 적 턴 행동을 건너뜁니다.',
  },
  {
    id: 'sk_confuse_shot',
    name: '교란 사격',
    action: 'debuff',
    apCost: 2,
    target: 'enemy',
    rangeMin: 3,
    rangeMax: 7,
    damageMul: 1,
    statusId: 'st_confuse',
    statusChance: 0.8,
    duration: 2,
    accuracyAdd: 0.02,
    desc: '무기 피해를 주고 80% 확률로 혼란을 부여합니다. 혼란 대상은 명중률이 20% 감소합니다.',
  },
  {
    id: 'sk_overwatch',
    name: '오버워치',
    action: 'overwatch',
    apCost: 2,
    target: 'self',
    rangeMin: 0,
    rangeMax: 0,
    overwatch: { duration: 1, shots: 1 },
    desc: '다음 적 턴까지 감시 태세에 들어갑니다. 사거리 안에서 적이 이동하면 1회 반응 사격합니다.',
  },
  {
    id: 'sk_rally',
    name: '사기 고양',
    action: 'buff',
    apCost: 2,
    target: 'self',
    rangeMin: 0,
    rangeMax: 0,
    teamwide: true,
    modifier: { stat: 'Accuracy', add: 0.1, duration: 2 },
    desc: '생존한 아군 전체의 명중률을 2턴 동안 10% 높입니다. 같은 스탯 효과는 가장 강한 수치만 적용됩니다.',
  },
  {
    id: 'sk_mark_target',
    name: '표식',
    action: 'debuff',
    apCost: 1,
    target: 'enemy',
    rangeMin: 3,
    rangeMax: 8,
    damageMul: 0,
    modifier: { stat: 'Evasion', add: -0.1, duration: 2 },
    desc: '대상의 회피를 2턴 동안 10% 낮춰 아군의 후속 공격 명중률을 높입니다.',
  },
  {
    id: 'sk_suppress',
    name: '제압 사격',
    action: 'debuff',
    apCost: 2,
    target: 'enemy',
    rangeMin: 3,
    rangeMax: 8,
    damageMul: 0.9,
    accuracyAdd: -0.1,
    modifier: { stat: 'Move', add: -1, duration: 1 },
    desc: '피해를 주고 대상의 이동력을 1턴 동안 1 낮춥니다.',
  },
  {
    id: 'sk_smoke_grenade',
    name: '연막 전개',
    action: 'smoke',
    apCost: 2,
    target: 'self',
    rangeMin: 0,
    rangeMax: 0,
    zone: { type: 'Smoke', radius: 1, duration: 2, accuracyMod: -0.2 },
    desc: '현재 위치 반경 1칸에 2라운드 연막을 만듭니다. 연막 안팎을 오가는 사격 명중률이 20% 감소합니다.',
  },
  {
    id: 'sk_breach_shot',
    name: '엄폐 파쇄탄',
    action: 'cover-break',
    apCost: 2,
    target: 'enemy',
    rangeMin: 2,
    rangeMax: 7,
    damageMul: 1,
    accuracyAdd: -0.08,
    coverDamage: 6,
    desc: '대상 칸의 엄폐 내구도를 먼저 6 깎은 뒤 공격합니다. 파괴된 엄폐는 방어 보너스를 잃습니다.',
  },
  {
    id: 'sk_burst',
    name: '점사',
    action: 'burst',
    apCost: 2,
    target: 'enemy',
    rangeMin: 2,
    rangeMax: 7,
    damageMul: 0.72,
    hits: 2,
    accuracyAdd: -0.05,
    desc: '명중 판정을 두 번 수행합니다. 각 탄은 낮은 피해를 주지만 보호막과 약한 적을 정리하기 좋습니다.',
  },
];

export const RECIPES = [
  { id: 'r_bandage', name: '붕대 만들기', inputs: [{ itemId: 'mat_wood', qty: 2 }], outputs: [{ itemId: 'con_bandage', qty: 1 }], costCredit: 5, requiredFacility: 'workbench' },
  { id: 'r_knife', name: '나이프 제작', inputs: [{ itemId: 'mat_stone', qty: 2 }, { itemId: 'mat_wood', qty: 1 }], outputs: [{ itemId: 'eq_knife', qty: 1 }], costCredit: 10, requiredFacility: 'workbench' },
];

export const SHOP_ITEMS = [
  { itemId: 'mat_wood', price: 2, stock: 30 },
  { itemId: 'mat_stone', price: 3, stock: 30 },
  { itemId: 'con_bandage', price: 8, stock: 10 },
  { itemId: 'eq_knife', price: 30, stock: 1 },
];

export const ECONOMY = {
  startingCredit: 500,
  innRestCost: 50,
  shop: { priceMulMin: 0.9, priceMulMax: 1.1, stockBumpMax: 3 },
  guild: {
    rankTable: [
      { minRep: 0, rank: 'F', nextRep: 100 },
      { minRep: 100, rank: 'E', nextRep: 250 },
      { minRep: 250, rank: 'D', nextRep: 500 },
      { minRep: 500, rank: 'C', nextRep: 1000 },
      { minRep: 1000, rank: 'B', nextRep: 2000 },
      { minRep: 2000, rank: 'A', nextRep: 4000 },
      { minRep: 4000, rank: 'S', nextRep: null },
    ],
  },
};

export const PROPERTIES = [
  {
    id: 'prop_shop_kiosk',
    name: '상가 키오스크',
    facility: 'shop',
    facilityLabel: '상점',
    district: 'market',
    icon: '상',
    effectLabel: '상점 가격 변동 완화',
    upgradeLabel: '가격 안정화',
    maxLevel: 3,
    upgradeBaseCost: 260,
    buyPrice: 900,
    rentFee: 150,
    rentCostPerDay: 15,
    leaseIncomePerDay: 40,
    desc: '상점과 연결되는 소형 점포입니다. 상점 가격 변동 폭을 낮춥니다.',
  },
  {
    id: 'prop_guild_branch',
    name: '길드 지부 사무실',
    facility: 'guild',
    facilityLabel: '길드',
    district: 'plaza',
    icon: '길',
    effectLabel: '의뢰 평판 보너스',
    upgradeLabel: '평판 업무 확장',
    maxLevel: 3,
    upgradeBaseCost: 340,
    buyPrice: 1400,
    rentFee: 220,
    rentCostPerDay: 25,
    leaseIncomePerDay: 65,
    desc: '길드 평판/랭크 업무를 돕는 사무실입니다. 의뢰 평판 보상이 10% 증가합니다.',
  },
  {
    id: 'prop_inn_room',
    name: '여관 전용 객실',
    facility: 'inn',
    facilityLabel: '여관',
    district: 'lodging',
    icon: '숙',
    effectLabel: '휴식 비용 감소',
    upgradeLabel: '객실 정비',
    maxLevel: 3,
    upgradeBaseCost: 300,
    buyPrice: 1100,
    rentFee: 180,
    rentCostPerDay: 20,
    leaseIncomePerDay: 50,
    desc: '여관 숙박 품질을 개선합니다. 휴식 비용이 10% 감소합니다.',
  },
  {
    id: 'prop_craft_shed',
    name: '소형 제작 작업장',
    facility: 'craft',
    facilityLabel: '제작',
    district: 'market',
    icon: '제',
    effectLabel: '제작 비용 감소',
    upgradeLabel: '공구 확충',
    maxLevel: 3,
    upgradeBaseCost: 280,
    buyPrice: 1000,
    rentFee: 170,
    rentCostPerDay: 18,
    leaseIncomePerDay: 45,
    desc: '제작과 연동되는 작업장입니다. 제작 비용이 5% 감소합니다.',
  },
];

export const EDICTS = [
  {
    id: 'ed_shop_discount_5',
    name: '상업 장려령',
    desc: '이번 달 동안 상점 판매가가 5% 할인됩니다.',
    cadence: 'monthly',
    effects: [{ type: 'shop_price_multiplier', value: 0.95 }],
  },
  {
    id: 'ed_inn_rest_discount_10',
    name: '숙박 지원령',
    desc: '이번 달 동안 여관 휴식 비용이 10% 할인됩니다.',
    cadence: 'monthly',
    effects: [{ type: 'inn_rest_cost_multiplier', value: 0.9 }],
  },
];

export const QUESTS = [
  {
    id: 'q_bandage_delivery',
    title: '붕대 납품',
    text: '붕대 1개를 가져오면 간단한 보상을 드립니다.',
    cadence: 'daily',
    requirement: { type: 'haveItem', itemId: 'con_bandage', qty: 1 },
    reward: { credit: 80, items: [{ itemId: 'mat_wood', qty: 1 }] },
    repReward: 5,
  },
  {
    id: 'q_weekly_training',
    title: '주간 훈련 보고',
    text: '이번 주에 전투 2회 승리하고 보고하세요.',
    cadence: 'weekly',
    requirement: { type: 'battleWin', count: 2 },
    reward: { credit: 200, items: [{ itemId: 'mat_stone', qty: 1 }] },
    repReward: 10,
  },
  {
    id: 'q_monthly_supplies',
    title: '월간 보급',
    text: '이번 달 보급품으로 나무 3개를 전달하세요.',
    cadence: 'monthly',
    requirement: { type: 'haveItem', itemId: 'mat_wood', qty: 3 },
    reward: { credit: 350, items: [{ itemId: 'con_bandage', qty: 1 }] },
    repReward: 15,
  },
  {
    id: 'q_yearly_review',
    title: '연간 전투 성과',
    text: '올해 전투 5회 승리한 기록을 제출하세요.',
    cadence: 'yearly',
    requirement: { type: 'battleWin', count: 5 },
    reward: { credit: 900, items: [{ itemId: 'eq_knife', qty: 1 }] },
    repReward: 40,
  },
  {
    id: 'q_knife_check',
    title: '무기 점검',
    text: '나이프 장비 1개를 가져오면 크레딧을 드립니다.',
    cadence: 'once',
    requirement: { type: 'haveItem', itemId: 'eq_knife', qty: 1 },
    reward: { credit: 120, items: [] },
    repReward: 5,
  },
  {
    id: 'q_first_victory',
    title: '첫 승리 보고',
    text: '전투에서 1회 승리하고 보고하세요.',
    cadence: 'once',
    requirement: { type: 'battleWin', count: 1 },
    reward: { credit: 100, items: [{ itemId: 'con_bandage', qty: 1 }] },
    repReward: 3,
  },
];

export const OBSTACLES = new Set(['3,1', '3,2', '4,4']);
export const COVER = new Set(['2,0', '2,4', '5,3']);
export const AI_RULES = {
  takeCover: 'AI_TAKE_COVER',
  attackIfInRange: 'AI_ATTACK_IF_IN_RANGE',
  moveToAttack: 'AI_MOVE_TO_ATTACK',
  moveToward: 'AI_MOVE_TOWARD',
  wait: 'AI_WAIT',
};
export const AI_COVER_HP_RATIO = 0.42;
