export const CIVILIZATION_STYLE_NAME_OVERRIDES = Object.freeze({
  FIREMAKING: '불의 이용',
  STONE_TOOLS: '석기',
  CORDAGE: '끈 제작',
  HERBALISM: '약초학',
  SHELTER: '주거',
  CRAFTSMANSHIP: '장인 기술',
  ORAL_RECORDS: '구전 전통',
  TRAPPING: '덫',
  ARCHIVE: '기록 보존',
  BRONZE_WORKING: '청동기 가공',
  BASIC_SAILING: '항해',
  BOOKCRAFT: '제본술',
  LIBRARY: '도서관',
  OBSIDIAN_KNAPPING: '흑요석 세공',
  EARLY_THEOLOGY: '신학',
  BASIC_MATH: '수학',
  BASIC_PHILOSOPHY: '철학',
  EARLY_CONSTRUCTION: '건축술',
  EARLY_CIVIL_ENGINEERING: '토목 공학',
  FORTIFICATION: '방어 시설',
  ASTRONOMY_EARLY: '천문학',
  ROAD_BUILDING: '도로망',
  MEDICAL_CORPUS: '의학',
  LEVER_MECHANICS: '지레 원리',
  CROP_CALENDAR: '농경력',
  REPUBLICAN_COUNCIL: '공화정',
  CIVIC_LAW: '법전',
  EARLY_ART: '미술',
  EARLY_MUSIC: '음악',
  EARLY_HORSEBACK: '기마술',
  EARLY_IRONWORKING: '철기 가공',
  BASIC_SHIPBUILDING: '조선술',
  EARLY_CURRENCY: '화폐',
  EARLY_OPTICS: '광학',
  FEUDAL_CONTRACT: '봉건제',
  GUILD_SYSTEM: '길드',
  UNIVERSITY_TRADITION: '대학 제도',
  ADVANCED_METALLURGY: '금속 주조',
  DEEP_WATER_SHIPBUILDING: '대양 조선술',
  IMPROVED_AGRICULTURE: '농업 개량',
  CODIFIED_THEOLOGY: '교리',
  MOVABLE_TYPE_PRINTING: '인쇄술',
  GUNPOWDER_MILL: '화약',
  OCEANIC_CARTOGRAPHY: '대양 지도 제작',
  ARQUEBUS: '화승총',
  GALLEON_SHIPBUILDING: '갤리온',
  FIELD_ARTILLERY: '야전 포병',
  PHARMACOPOEIA: '약전',
  EARLY_STEAM_ENGINE: '증기력',
  CLASSICAL_MECHANICS: '역학',
  MODERN_AGRONOMY: '농학',
  STANDING_ARMY: '상비군',
  EMPIRICISM: '경험론',
  PATRONAGE_CULTURE: '후원제',
  CONFESSIONAL_TOLERANCE: '종교 관용',
  BUREAUCRATIC_STATE: '관료제',
  MILITARY_REVOLUTION: '군사 혁명',
  ENLIGHTENED_THEOLOGY: '자연신학',
  SOCIAL_CONTRACT: '사회 계약',
  CONSTITUTIONAL_ASSEMBLY: '입헌주의',
});

export const ADVANCEMENT_QUOTE_CATALOG = Object.freeze({
  labor: {
    text: '일은 수치가 아니다. 게으름이 수치다.',
    author: '헤시오도스',
    work: '일과 나날',
    sourceUrl: 'https://www.gutenberg.org/files/348/348-h/348-h.htm',
  },
  tools: {
    text: '도움 없는 손과 홀로 남겨진 이해력은 힘이 거의 없다. 결과는 도구와 보조 수단을 통해 만들어진다.',
    author: '프랜시스 베이컨',
    work: '신기관',
    sourceUrl: 'https://www.gutenberg.org/files/45988/45988-h/45988-h.htm',
  },
  fire: {
    text: '제우스가 불을 숨겼으나, 프로메테우스는 그것을 다시 인간에게 가져왔다.',
    author: '헤시오도스',
    work: '일과 나날',
    sourceUrl: 'https://www.gutenberg.org/files/348/348-h/348-h.htm',
  },
  pottery: {
    text: '진흙이 토기장이의 손에 있음 같이, 너희도 내 손에 있다.',
    author: '예레미야',
    work: '예레미야서 18장',
    sourceUrl: 'https://www.gutenberg.org/ebooks/10',
  },
  navigation: {
    text: '알맞은 항해일을 기다렸다가 빠른 배를 바다로 끌어내려라.',
    author: '헤시오도스',
    work: '일과 나날',
    sourceUrl: 'https://www.gutenberg.org/files/348/348-h/348-h.htm',
  },
  cartography: {
    text: '지도 제작은 알려진 세계와 그 안의 현상을 하나의 그림으로 나타내는 일이다.',
    author: '클라우디오스 프톨레마이오스',
    work: '지리학',
    sourceUrl: 'https://apps.lib.umn.edu/bell/map/PTO/GEO/mainptg.html',
  },
  shipbuilding: {
    text: '그는 재목을 다듬고 맞추어 튼튼한 상선의 바닥처럼 넓은 배를 만들었다.',
    author: '호메로스',
    work: '오디세이아 제5권',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/1728/pg1728-images.html',
  },
  hunting: {
    text: '사냥은 전쟁을 위한 최고의 훈련이며 기마술을 익히는 가장 확실한 길이다.',
    author: '크세노폰',
    work: '키루스의 교육',
    sourceUrl: 'https://www.gutenberg.org/files/2085/2085-h/2085-h.htm',
  },
  fishing: {
    text: '낚시는 말이 아니라 실천으로 배워야 한다.',
    author: '아이작 월턴',
    work: '낚시대전',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/683/pg683.html',
  },
  agriculture: {
    text: '여러 기술이 생겨났고, 고된 노동이 모든 것을 이겼다.',
    author: '베르길리우스',
    work: '농경시',
    sourceUrl: 'https://www.gutenberg.org/files/232/232-h/232-h.htm',
  },
  husbandry: {
    text: '말이 바라는 대로 움직였을 때 친절로 보답하면, 자기 임무를 더 잘 배운다.',
    author: '크세노폰',
    work: '승마술',
    sourceUrl: 'https://www.gutenberg.org/files/1176/1176-h/1176-h.htm',
  },
  medicine: {
    text: '인생은 짧고, 의술은 길며, 기회는 덧없다.',
    author: '히포크라테스',
    work: '격언',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/67833/pg67833-images.html',
  },
  architecture: {
    text: '모든 건축은 견고함, 편리함, 아름다움을 고려해야 한다.',
    author: '비트루비우스',
    work: '건축십서',
    sourceUrl: 'https://www.gutenberg.org/files/20239/20239-h/20239-h.htm',
  },
  aqueduct: {
    text: '수많은 물을 나르는 이 필수 구조물들을 쓸모없는 피라미드와 어찌 비교하겠는가.',
    author: '섹스투스 율리우스 프론티누스',
    work: '로마의 수도에 관하여',
    sourceUrl: 'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Frontinus/De_Aquis/Bennett/1%2A.html',
  },
  mathematics: {
    text: '기하학에는 왕도가 없다.',
    author: '유클리드',
    work: '프로클로스가 전한 일화',
    sourceUrl: 'https://www.gutenberg.org/files/37681/37681-h/37681-h.htm',
  },
  mechanics: {
    text: '내게 설 자리를 주면 지구를 움직이겠다.',
    author: '아르키메데스',
    work: '플루타르코스가 전한 일화',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/35550/pg35550-images.html',
  },
  waterPower: {
    text: '강물의 흐름이 물받이를 밀어 바퀴를 돌리고, 사람의 발힘 없이 필요한 일을 해낸다.',
    author: '비트루비우스',
    work: '건축십서 제10권',
    sourceUrl: 'https://www.gutenberg.org/files/20239/20239-h/20239-h.htm',
  },
  windPower: {
    text: '저것들은 거인이 아니라 풍차이며, 팔처럼 보이는 것은 바람이 돌려 맷돌을 움직이는 날개입니다.',
    author: '미겔 데 세르반테스',
    work: '돈키호테 제1부 제8장',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/5921/pg5921-images.html',
  },
  steam: {
    text: '열이 운동을 만들어 낸다는 것은 누구나 안다. 증기기관이 널리 알려진 지금, 그 거대한 동력을 의심할 수 없다.',
    author: '사디 카르노',
    work: '열의 동력에 관한 고찰',
    sourceUrl: 'https://www.gutenberg.org/ebooks/78610',
  },
  refrigeration: {
    text: '동력을 낳으려면 열뿐 아니라 냉기도 필요하다. 냉기가 없다면 열은 쓸모가 없다.',
    author: '사디 카르노',
    work: '열의 동력에 관한 고찰',
    sourceUrl: 'https://www.gutenberg.org/ebooks/78610',
  },
  military: {
    text: '옛 명장은 먼저 패배할 수 없는 태세를 갖춘 뒤, 적을 이길 기회를 기다렸다.',
    author: '손자',
    work: '손자병법',
    sourceUrl: 'https://www.gutenberg.org/files/17405/17405-h/17405-h.htm',
  },
  polity: {
    text: '인간은 본성상 정치적 동물이다.',
    author: '아리스토텔레스',
    work: '정치학',
    sourceUrl: 'https://www.gutenberg.org/files/6762/6762-h/6762-h.htm',
  },
  law: {
    text: '법이 끝나는 곳에서 폭정이 시작된다.',
    author: '존 로크',
    work: '통치론 제2편',
    sourceUrl: 'https://www.gutenberg.org/files/7370/7370-h/7370-h',
  },
  liberty: {
    text: '인간은 자유롭게 태어났지만, 어디서나 사슬에 묶여 있다.',
    author: '장 자크 루소',
    work: '사회계약론',
    sourceUrl: 'https://www.gutenberg.org/files/46333/46333-h/46333-h.htm',
  },
  economy: {
    text: '노동 생산력의 가장 큰 향상은 분업의 결과로 보인다.',
    author: '애덤 스미스',
    work: '국부론',
    sourceUrl: 'https://www.gutenberg.org/files/3300/3300-h/3300-h',
  },
  trade: {
    text: '사람에게는 한 물건을 다른 물건과 교환하고 거래하려는 성향이 있다.',
    author: '애덤 스미스',
    work: '국부론',
    sourceUrl: 'https://www.gutenberg.org/files/3300/3300-h/3300-h',
  },
  currency: {
    text: '교역의 불편을 덜기 위해 운반하기 쉬운 물건을 정하고, 마침내 그 가치의 표지를 새겼다.',
    author: '아리스토텔레스',
    work: '정치학',
    sourceUrl: 'https://www.gutenberg.org/files/6762/6762-h/6762-h.htm',
  },
  industry: {
    text: '분업이 진전될수록 같은 수의 사람이 해낼 수 있는 일의 양은 크게 늘어난다.',
    author: '애덤 스미스',
    work: '국부론',
    sourceUrl: 'https://www.gutenberg.org/files/3300/3300-h/3300-h',
  },
  faith: {
    text: '우리 마음은 당신 안에서 쉴 때까지 안식을 얻지 못합니다.',
    author: '아우구스티누스',
    work: '고백록',
    sourceUrl: 'https://www.gutenberg.org/files/3296/3296-h/3296-h.htm',
  },
  inquiry: {
    text: '지식과 인간의 힘은 하나다.',
    author: '프랜시스 베이컨',
    work: '신기관',
    sourceUrl: 'https://www.gutenberg.org/files/45988/45988-h/45988-h.htm',
  },
  experiment: {
    text: '자연은 복종함으로써만 정복된다.',
    author: '프랜시스 베이컨',
    work: '신기관',
    sourceUrl: 'https://www.gutenberg.org/files/45988/45988-h/45988-h.htm',
  },
  records: {
    text: '독서는 사람을 충실하게 하고, 토론은 준비되게 하며, 글쓰기는 정확하게 한다.',
    author: '프랜시스 베이컨',
    work: '수상록 - 학문에 대하여',
    sourceUrl: 'https://www.gutenberg.org/files/575/575-h/575-h.htm',
  },
  oralTradition: {
    text: '살아 있고 영혼을 지닌 지식의 말에 비하면, 글로 적힌 말은 그 그림자일 뿐이다.',
    author: '플라톤',
    work: '파이드로스',
    sourceUrl: 'https://www.gutenberg.org/files/1636/1636-h/1636-h.htm',
  },
  writing: {
    text: '글자는 기억 그 자체가 아니라, 기억을 되살리는 도움이다.',
    author: '플라톤',
    work: '파이드로스',
    sourceUrl: 'https://www.gutenberg.org/files/1636/1636-h/1636-h.htm',
  },
  history: {
    text: '역사는 시대의 증인이며, 진리의 빛이고, 기억의 삶이며, 인생의 스승이다.',
    author: '마르쿠스 툴리우스 키케로',
    work: '웅변가론',
    sourceUrl: 'https://www.gutenberg.org/ebooks/9776',
  },
  education: {
    text: '교육이 처음 사람을 이끄는 방향이 그의 장래를 결정한다.',
    author: '플라톤',
    work: '국가',
    sourceUrl: 'https://www.gutenberg.org/ebooks/1497',
  },
  nature: {
    text: '자연은 가장 작은 작품에서 가장 완전하게 드러난다.',
    author: '대 플리니우스',
    work: '박물지',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/59131/pg59131-images.html',
  },
  astronomy: {
    text: '태양을 중심으로 수성, 금성, 지구, 화성, 목성, 토성의 궤도가 차례로 놓인다.',
    author: '크리스티안 하위헌스',
    work: '천체 세계의 발견',
    sourceUrl: 'https://www.gutenberg.org/files/71191/71191-h/71191-h.htm',
  },
  astrology: {
    text: '별의 본성을 아는 숙련자는 그 영향에 미리 대비할 수 있다.',
    author: '클라우디오스 프톨레마이오스',
    work: '테트라비블로스',
    sourceUrl: 'https://www.gutenberg.org/files/70850/70850-h/70850-h.htm',
  },
  drama: {
    text: '온 세상은 무대이고, 모든 남녀는 배우일 뿐이다.',
    author: '윌리엄 셰익스피어',
    work: '뜻대로 하세요',
    sourceUrl: 'https://www.gutenberg.org/ebooks/1523',
  },
  poetry: {
    text: '시는 삶의 의무를 가르치고 미래를 밝혔으며, 노동 뒤에는 즐거운 휴식을 주었다.',
    author: '호라티우스',
    work: '시학',
    sourceUrl: 'https://www.gutenberg.org/ebooks/5419',
  },
  epic: {
    text: '노래하소서, 여신이여, 펠레우스의 아들 아킬레우스의 분노를.',
    author: '호메로스',
    work: '일리아스',
    sourceUrl: 'https://www.gutenberg.org/ebooks/16452',
  },
  rhetoric: {
    text: '수사학은 변증술과 짝을 이룬다.',
    author: '아리스토텔레스',
    work: '수사학',
    sourceUrl: 'https://classics.mit.edu/Aristotle/rhetoric.1.i.html',
  },
  time: {
    text: '그렇다면 시간이란 무엇인가?',
    author: '아우구스티누스',
    work: '고백록 제11권',
    sourceUrl: 'https://www.gutenberg.org/files/3296/3296-h/3296-h.htm',
  },
  philosophy: {
    text: '나는 생각한다. 그러므로 나는 존재한다.',
    author: '르네 데카르트',
    work: '방법서설',
    sourceUrl: 'https://www.gutenberg.org/files/59/59-h/59-h.htm',
  },
  enlightenment: {
    text: '자기 자신의 이성을 사용할 용기를 가져라.',
    author: '임마누엘 칸트',
    work: '계몽이란 무엇인가',
    sourceUrl: 'https://www.gutenberg.org/files/30821/30821-h/30821-h.htm',
  },
  utilitarianism: {
    text: '행위는 행복을 증진하는 경향에 비례하여 옳고, 그 반대를 낳는 경향에 비례하여 그르다.',
    author: '존 스튜어트 밀',
    work: '공리주의',
    sourceUrl: 'https://www.gutenberg.org/ebooks/11224',
  },
  humanism: {
    text: '나는 인간이다. 인간적인 어떤 것도 나와 무관하지 않다.',
    author: '테렌티우스',
    work: '자기 자신을 괴롭히는 자',
    sourceUrl: 'https://www.gutenberg.org/ebooks/39526',
  },
  metallurgy: {
    text: '광부는 무엇을 캐고 무엇을 남겨둘지 알 만큼 자기 일에 숙련되어야 한다.',
    author: '게오르기우스 아그리콜라',
    work: '데 레 메탈리카',
    sourceUrl: 'https://www.gutenberg.org/ebooks/38015',
  },
  steelmaking: {
    text: '철의 시대는 지나가고 강철의 시대가 그 자리를 차지할 운명이었다.',
    author: '앤드루 카네기',
    work: '자서전',
    sourceUrl: 'https://www.gutenberg.org/files/17976/17976-h/17976-h.htm',
  },
  glassmaking: {
    text: '불이 붙자 초석이 해변의 모래와 섞였고, 전에는 보지 못한 투명한 액체가 흘러나왔다.',
    author: '대 플리니우스',
    work: '박물지 제36권',
    sourceUrl: 'https://www.gutenberg.org/files/50626/50626-h/50626-h.htm',
  },
  optics: {
    text: '빛의 성질은 가설이 아니라 이성과 실험으로 제시하고 증명해야 한다.',
    author: '아이작 뉴턴',
    work: '광학',
    sourceUrl: 'https://www.gutenberg.org/files/33504/33504-h/33504-h.htm',
  },
  microscopy: {
    text: '현미경의 도움을 받으면 너무 작아서 탐구를 피할 것은 없다.',
    author: '로버트 훅',
    work: '미크로그라피아',
    sourceUrl: 'https://www.gutenberg.org/ebooks/15491',
  },
  empiricism: {
    text: '진리에 이르는 가장 좋은 길은 사물을 상상대로가 아니라 실제 모습대로 살피는 것이다.',
    author: '존 로크',
    work: '인간오성론',
    sourceUrl: 'https://www.gutenberg.org/ebooks/10615',
  },
  art: {
    text: '사람의 아름다움은 사라지지만, 예술 속의 아름다움은 사라지지 않는다.',
    author: '레오나르도 다 빈치',
    work: '노트북',
    sourceUrl: 'https://www.gutenberg.org/ebooks/5000',
  },
  music: {
    text: '음악은 교육과 영혼의 정화, 그리고 마음의 휴식에 쓰여야 한다.',
    author: '아리스토텔레스',
    work: '정치학',
    sourceUrl: 'https://www.gutenberg.org/ebooks/6762',
  },
  tolerance: {
    text: '참된 신앙은 마음속 확신에 있으므로, 외적인 힘으로 믿음을 강제할 수 없다.',
    author: '존 로크',
    work: '관용에 관한 편지',
    sourceUrl: 'https://self.gutenberg.org/wplbn0000651234-a-letter-concerning-toleration-by-locke-john.aspx',
  },
  press: {
    text: '알고 말하고 양심에 따라 자유롭게 논할 자유를 달라.',
    author: '존 밀턴',
    work: '아레오파지티카',
    sourceUrl: 'https://www.gutenberg.org/ebooks/608',
  },
  printing: {
    text: '인쇄술, 화약, 나침반은 세계의 모습과 상태를 완전히 바꾸었다.',
    author: '프랜시스 베이컨',
    work: '신기관',
    sourceUrl: 'https://www.gutenberg.org/files/45988/45988-h/45988-h.htm',
  },
  gunpowder: {
    text: '인쇄술, 화약, 나침반은 세계의 모습과 상태를 완전히 바꾸었다.',
    author: '프랜시스 베이컨',
    work: '신기관',
    sourceUrl: 'https://www.gutenberg.org/files/45988/45988-h/45988-h.htm',
  },
  monasticism: {
    text: '게으름은 영혼의 적이다. 정해진 때에는 노동하고, 정해진 때에는 성스러운 독서에 힘써야 한다.',
    author: '누르시아의 베네딕투스',
    work: '성 베네딕투스 규칙서 제48장',
    sourceUrl: 'https://en.wikisource.org/wiki/Select_Historical_Documents_of_the_Middle_Ages/Book_III/The_Rule_of_St._Benedict',
  },
  feudalLaw: {
    text: '자유인은 동료의 적법한 판결이나 국법에 의하지 않고는 체포되거나 권리를 빼앗기지 않는다.',
    author: '잉글랜드의 존 왕과 제후들',
    work: '마그나 카르타 제39조',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/10000/pg10000-images.html',
  },
  chivalry: {
    text: '잔혹함을 피하고 자비를 구하는 이에게 자비를 베풀며, 부당한 싸움에 나서지 말라.',
    author: '토머스 맬러리',
    work: '아서 왕의 죽음',
    sourceUrl: 'https://www.gutenberg.org/cache/epub/1251/pg1251-images.html',
  },
  scientificSociety: {
    text: '우리 재단의 목적은 사물의 원인과 숨은 움직임을 아는 데 있다.',
    author: '프랜시스 베이컨',
    work: '새로운 아틀란티스',
    sourceUrl: 'https://www.gutenberg.org/files/2434/2434-h/2434-h.htm',
  },
  maritimeLaw: {
    text: '바다는 누구의 소유도 될 수 없을 만큼 한계가 없고, 항해와 어업을 위해 모두에게 열려 있다.',
    author: '휘호 흐로티위스',
    work: '자유해론',
    sourceUrl: 'https://www.gutenberg.org/files/75962/75962-h/75962-h.htm',
  },
  welfare: {
    text: '공공 창고를 가득 채우도록 돌본다면 어느 개인도 필요한 것을 잃지 않는다.',
    author: '토머스 모어',
    work: '유토피아',
    sourceUrl: 'https://www.gutenberg.org/files/2130/2130-h/2130-h.htm',
  },
  constitution: {
    text: '입법권과 집행권이 한 사람이나 한 기관에 합쳐지면 자유는 존재할 수 없다.',
    author: '샤를 드 몽테스키외',
    work: '법의 정신',
    sourceUrl: 'https://www.gutenberg.org/ebooks/27573',
  },
  liberalism: {
    text: '타인의 행복을 빼앗지 않는 한, 자기 방식으로 자기 행복을 추구하는 자유만이 참된 자유다.',
    author: '존 스튜어트 밀',
    work: '자유론',
    sourceUrl: 'https://gutenberg.org/files/34901/34901-h/34901-h.htm',
  },
  chemistry: {
    text: '우리는 사실만을 신뢰해야 한다. 자연이 내놓은 사실은 우리를 속이지 않는다.',
    author: '앙투안 라부아지에',
    work: '화학 원론',
    sourceUrl: 'https://www.gutenberg.org/ebooks/30775',
  },
  electricity: {
    text: '자기에서 전기를 얻으려는 희망이 나를 실험적 탐구로 이끌었다.',
    author: '마이클 패러데이',
    work: '전기 실험 연구',
    sourceUrl: 'https://www.gutenberg.org/ebooks/14986',
  },
  telegraphy: {
    text: '하느님이 무슨 일을 이루셨는가.',
    author: '새뮤얼 모스가 보낸 최초의 전신 문구',
    work: '최초의 전신 메시지, 1844년 5월 24일',
    sourceUrl: 'https://www.loc.gov/item/mcc.019/',
  },
  publicHealth: {
    text: '간호의 첫 원칙은 환자가 마시는 공기를 바깥 공기만큼 깨끗하게 유지하는 것이다.',
    author: '플로렌스 나이팅게일',
    work: '간호론',
    sourceUrl: 'https://www.gutenberg.org/ebooks/12439',
  },
  vaccination: {
    text: '우두는 인간의 몸을 천연두 감염으로부터 지켜 준다.',
    author: '에드워드 제너',
    work: '우두의 원인과 효과에 관한 연구',
    sourceUrl: 'https://www.gutenberg.org/files/29414/29414-h/29414-h.htm',
  },
  germTheory: {
    text: '발효체는 조직된 생명이며, 그 싹은 언제나 이미 존재한다.',
    author: '루이 파스퇴르',
    work: '발효에 관한 연구',
    sourceUrl: 'https://www.gutenberg.org/files/63355/63355-h/63355-h.htm',
  },
  anatomy: {
    text: '모든 세부가 분명히 보여, 각 해부도가 한 장의 그림처럼 보여야 한다.',
    author: '안드레아스 베살리우스',
    work: '오포리누스에게 보낸 편지',
    sourceUrl: 'https://www.gutenberg.org/files/63456/63456-h/63456-h.htm',
  },
  photography: {
    text: '이 그림들은 화가의 연필 없이, 빛이 감광지에 작용하여 만들어졌다.',
    author: '윌리엄 헨리 폭스 탤벗',
    work: '자연의 연필',
    sourceUrl: 'https://www.gutenberg.org/ebooks/33447.html.images',
  },
  humanitarianRelief: {
    text: '평시에 구호 단체를 만들어, 전시의 부상자를 헌신적이고 숙련된 자원봉사자가 돌보게 할 수 없겠는가.',
    author: '앙리 뒤낭',
    work: '솔페리노의 회상',
    sourceUrl: 'https://www.gutenberg.org/files/52524/52524-h/52524-h.htm',
  },
  laborRights: {
    text: '공장에서는 법률과 현실에서의 자유가 모두 끝난다.',
    author: '프리드리히 엥겔스',
    work: '1844년 영국 노동계급의 상태',
    sourceUrl: 'https://www.gutenberg.org/files/17306/17306-h/17306-h.htm',
  },
  foodPreservation: {
    text: '이 방법은 헛된 이론이 아니다. 성찰과 탐구, 오랜 주의와 수많은 실험의 결실이다.',
    author: '니콜라 아페르',
    work: '동식물성 물질을 오랫동안 보존하는 법',
    sourceUrl: 'https://www.gutenberg.org/ebooks/52551',
  },
  athletics: {
    text: '체육은 몸을 단련하고, 올바른 교육은 품성을 기른다.',
    author: '아리스토텔레스',
    work: '정치학',
    sourceUrl: 'https://www.gutenberg.org/ebooks/6762',
  },
});

export const ADVANCEMENT_QUOTE_ASSIGNMENTS = Object.freeze({
  tools: ['STONE_TOOLS', 'CORDAGE', 'CRAFTSMANSHIP', 'ADVANCED_CARVING', 'OBSIDIAN_KNAPPING', 'STEEL_TOOLS'],
  fire: ['FIREMAKING', 'HEARTH'],
  pottery: ['POTTERY'],
  navigation: ['BASIC_SAILING', 'LATEEN_SAIL', 'NAVIGATION', 'OCEAN_NAVIGATION', 'CELESTIAL_NAVIGATION', 'POWERED_FLIGHT'],
  cartography: ['CARTOGRAPHY', 'OCEANIC_CARTOGRAPHY'],
  shipbuilding: [
    'BASIC_SHIPBUILDING', 'HULL_FRAMING', 'DEEP_WATER_SHIPBUILDING', 'GALLEON_SHIPBUILDING',
    'SHIP_OF_THE_LINE', 'IRONCLAD_SHIPBUILDING', 'TURBINE_WARSHIP',
  ],
  hunting: ['HUNTING', 'TRAPPING', 'MEGAFAUNA_HIDE'],
  fishing: ['FISHING'],
  agriculture: [
    'AGRICULTURE', 'IRRIGATION', 'CROP_CALENDAR', 'THREE_FIELD_SYSTEM', 'HEAVY_PLOUGH',
    'CROP_ROTATION', 'IMPROVED_AGRICULTURE', 'NEW_CROP_CULTIVATION', 'SEED_SELECTION',
    'MODERN_AGRONOMY', 'MECHANIZED_FARMING', 'AGRARIAN_REFORM',
  ],
  husbandry: ['ANIMAL_HUSBANDRY'],
  nature: ['GATHERING', 'BOTANICAL_CLASSIFICATION'],
  medicine: [
    'HERBALISM', 'MEDICAL_CORPUS', 'SURGICAL_TOOLS', 'HERBAL_MEDICINE', 'MEDIEVAL_MEDICINE',
    'PHARMACOPOEIA', 'MISSIONARY_MEDICINE', 'ANTISEPTIC_SURGERY', 'EMERGENCY_MEDICINE',
    'BLOOD_TYPING',
  ],
  anatomy: ['ANATOMICAL_STUDY'],
  publicHealth: [
    'PUBLIC_HEALTH', 'HOSPITAL_SANITATION', 'MODERN_HOSPITAL', 'PUBLIC_SANITATION',
    'DISTRICT_NURSING', 'X_RAY_IMAGING',
  ],
  vaccination: ['VACCINATION'],
  germTheory: ['GERM_THEORY', 'PASTEURIZATION', 'BACTERIOLOGICAL_LAB'],
  foodPreservation: ['FOOD_STORAGE', 'FOOD_CANNING'],
  architecture: [
    'SHELTER', 'SETTLEMENT', 'EARLY_CONSTRUCTION', 'EARLY_CIVIL_ENGINEERING', 'FORTIFICATION',
    'ROAD_BUILDING', 'MASONRY_VAULTS', 'CASTLE_ENGINEERING', 'TRACE_ITALIENNE',
  ],
  aqueduct: ['AQUEDUCT_ENGINEERING'],
  mathematics: ['COUNTING', 'BASIC_MATH'],
  mechanics: ['LEVER_MECHANICS', 'MECHANICAL_ENGINEERING', 'DRAINAGE_PUMP', 'CLASSICAL_MECHANICS'],
  waterPower: ['WATERMILL'],
  windPower: ['WINDMILL'],
  steam: [
    'STEAM_PUMP', 'EARLY_STEAM_ENGINE', 'ROTARY_STEAM_POWER', 'RAILWAY_ENGINEERING',
    'THERMODYNAMICS', 'INTERNAL_COMBUSTION_ENGINE', 'AUTOMOBILE',
  ],
  refrigeration: ['REFRIGERATION', 'COLD_CHAIN'],
  metallurgy: [
    'MINING', 'BRONZE_WORKING', 'EARLY_IRONWORKING', 'STEEL_QUENCHING', 'BLOOMERY_FURNACE',
    'ADVANCED_METALLURGY',
  ],
  steelmaking: ['BESSEMER_STEEL'],
  military: [
    'ARCHERY', 'MILITARY_TRADITION', 'EARLY_HORSEBACK', 'MILITARY_TRAINING',
    'DEFENSE_TACTICS', 'CHAINMAIL', 'PLATE_ARMOR', 'ARQUEBUS', 'FIELD_ARTILLERY',
    'STANDING_ARMY', 'MILITARY_REVOLUTION', 'PROFESSIONAL_OFFICERS', 'RIFLED_MUSKET',
    'BREECH_LOADING_RIFLE', 'STEEL_ARTILLERY', 'MASS_CONSCRIPTION', 'GENERAL_STAFF',
  ],
  chivalry: ['CHIVALRIC_CODE', 'MILITARY_ORDERS'],
  athletics: ['ATHLETIC_GAMES'],
  polity: [
    'EARLY_EMPIRE', 'REPUBLICAN_COUNCIL', 'IMPERIAL_ADMINISTRATION', 'BUREAUCRATIC_STATE',
    'URBAN_CHARTER', 'STATE_WORKFORCE', 'MUNICIPAL_GOVERNMENT', 'NATION_STATE',
    'NATIONAL_MOBILIZATION', 'REGULATED_UTILITIES',
  ],
  feudalLaw: ['FEUDAL_CONTRACT', 'ESTATES_ASSEMBLY'],
  law: ['CIVIC_LAW', 'INTERNATIONAL_LAW'],
  maritimeLaw: ['MARITIME_LAW'],
  liberty: ['SOCIAL_CONTRACT', 'UNIVERSAL_SUFFRAGE'],
  constitution: ['CONSTITUTIONAL_ASSEMBLY'],
  liberalism: ['LIBERALISM'],
  tolerance: ['CONFESSIONAL_TOLERANCE', 'RELIGIOUS_LIBERTY', 'ECUMENICAL_MOVEMENT', 'RELIGIOUS_PLURALISM'],
  economy: ['GUILD_SYSTEM'],
  trade: ['FOREIGN_TRADE'],
  currency: ['EARLY_CURRENCY'],
  industry: ['POWER_LOOM', 'INDUSTRIAL_ENTREPRENEURSHIP', 'FACTORY_SYSTEM', 'CORPORATE_ENTERPRISE'],
  faith: [
    'MYSTICISM', 'EARLY_THEOLOGY', 'CIVIC_RITUAL', 'SCHOLASTICISM', 'CODIFIED_THEOLOGY',
    'REFORMATION', 'ENLIGHTENED_THEOLOGY', 'EVANGELICAL_REVIVAL', 'SOCIAL_GOSPEL',
  ],
  monasticism: ['MONASTIC_RULE'],
  oralTradition: ['ORAL_RECORDS'],
  writing: ['ARCHIVE', 'WRITING', 'CLAY_TABLETS'],
  records: ['BOOKCRAFT', 'LIBRARY', 'PAPERMAKING'],
  history: ['HISTORY_RECORDS', 'CHRONICLE_WRITING'],
  education: [
    'CLASSICAL_EDUCATION', 'CATHEDRAL_SCHOOLS', 'UNIVERSITY_TRADITION', 'PUBLIC_EDUCATION',
    'RESEARCH_UNIVERSITY', 'COMPULSORY_EDUCATION', 'PROFESSIONAL_LICENSING',
  ],
  rhetoric: ['RHETORIC'],
  press: ['PUBLIC_DEBATE', 'PUBLIC_SPHERE', 'FREEDOM_OF_PRESS', 'MASS_JOURNALISM'],
  printing: [
    'PRINTING_BLOCKS', 'MOVABLE_TYPE_PRINTING', 'PRINT_WORKSHOP', 'COPPERPLATE_PRINTING',
    'STEAM_PRINTING_PRESS', 'MASS_PUBLISHING',
  ],
  astronomy: ['ASTRONOMY_EARLY'],
  astrology: ['ASTROLOGY'],
  glassmaking: ['GLASSMAKING'],
  optics: ['EARLY_OPTICS', 'OPTICAL_INSTRUMENTS'],
  microscopy: ['MICROSCOPE'],
  drama: ['DRAMA'],
  epic: ['EPIC_TRADITION'],
  poetry: ['POETRY', 'COURT_LITERATURE', 'ROMANCE_LITERATURE'],
  art: ['EARLY_ART', 'PATRONAGE_CULTURE'],
  photography: ['PHOTOGRAPHY', 'MOTION_PICTURES'],
  music: ['EARLY_MUSIC', 'SACRED_MUSIC', 'PHONOGRAPH'],
  time: ['CALENDAR', 'MECHANICAL_CLOCK', 'PRECISION_CLOCK', 'STANDARD_TIME'],
  philosophy: ['BASIC_PHILOSOPHY', 'CLASSICAL_PHILOSOPHY', 'NATURAL_PHILOSOPHY'],
  enlightenment: ['ENLIGHTENMENT'],
  utilitarianism: ['UTILITARIANISM'],
  experiment: ['SCIENTIFIC_METHOD'],
  empiricism: ['EMPIRICISM', 'POSITIVISM', 'PROFESSIONAL_SCIENCE'],
  scientificSociety: ['SCIENTIFIC_SOCIETY', 'STATISTICAL_ADMINISTRATION'],
  gunpowder: ['GUNPOWDER_MILL', 'MACHINE_GUN', 'SMOKELESS_POWDER'],
  chemistry: ['MODERN_CHEMISTRY', 'ORGANIC_CHEMISTRY', 'PERIODIC_LAW', 'ARTIFICIAL_FERTILIZER', 'ATOMIC_THEORY'],
  electricity: ['ELECTROMAGNETISM', 'ELECTRIC_GENERATION', 'ELECTRIC_GRID'],
  telegraphy: ['TELEGRAPHY', 'TELEPHONE', 'WIRELESS_TELEGRAPHY'],
  humanism: ['HUMANISM', 'RENAISSANCE_HUMANISM', 'HUMANITARIANISM'],
  welfare: ['POOR_RELIEF', 'SOCIAL_INSURANCE', 'MUNICIPAL_WELFARE'],
  humanitarianRelief: ['HUMANITARIAN_LOGISTICS', 'HAGUE_CONVENTIONS'],
  laborRights: ['LABOR_PROTECTION', 'TRADE_UNIONISM'],
});

const QUOTE_KEY_BY_ADVANCEMENT_ID = Object.freeze(Object.fromEntries(
  Object.entries(ADVANCEMENT_QUOTE_ASSIGNMENTS).flatMap(([quoteKey, ids]) => ids.map((id) => [id, quoteKey])),
));

function fallbackQuoteKey(advancement) {
  const tags = advancement.tags || [];
  if (tags.includes('SPIRITUAL')) return 'faith';
  if (tags.includes('MILITARY')) return 'military';
  if (tags.includes('CIVICS')) return 'polity';
  if (tags.includes('CULTURE')) return 'records';
  if (tags.includes('SCIENCE')) return 'inquiry';
  if (tags.includes('CRAFT') || tags.includes('CAMP')) return 'experiment';
  return 'labor';
}

export function withAdvancementLore(advancement) {
  const assignedQuoteKey = QUOTE_KEY_BY_ADVANCEMENT_ID[advancement.id] || '';
  const quoteKey = assignedQuoteKey || fallbackQuoteKey(advancement);
  return {
    ...advancement,
    name: CIVILIZATION_STYLE_NAME_OVERRIDES[advancement.id] || advancement.name,
    quote: {
      ...ADVANCEMENT_QUOTE_CATALOG[quoteKey],
      key: quoteKey,
      explicit: Boolean(assignedQuoteKey),
    },
  };
}
